### ISSUE TITLE
[FER] standalone date picker component

### ISSUE THREAD

**Issue by yw662** [schedule-x/schedule-x#143]
**Is your feature request related to a problem? Please describe.**
Not particularly.

**Describe the solution you'd like**
as in https://tomosterlund.github.io/qalendar/guide.html#date-picker, would this date picker be able to be used as a standalone component ?

**Comment by tomosterlund** [comment]
Hi. You have opened an issue in the wrong repo. This is the issue tracker of another project. But the short answer would be yes, you can :)

**Comment by yw662** [comment]
@tomosterlund But where should I open this issue for @schedule-x/date-picker ?

**Comment by tomosterlund** [comment]
The `@schedule-x/date-picker` is developed in this repository. You can also already use this as a stand alone date picker 😊Documentation for this can be found here: https://schedule-x.dev/docs/date-picker

**Comment by yw662** [comment]
Hmm but what if I want to use the popup month view as a standalone component ?

**Comment by tomosterlund** [comment]
I'm sorry, but that does currently not fit in the project roadmap to offer only the popup as a component. I might consider this, if I end up offering a calendar sidebar with a date picker, similar to how Google Calendar does it. That is not yet part of the plan however.

**Comment by yw662** [comment]
Maybe I can do it and make a PR here. Any suggestions for that ?
