### ISSUE TITLE
feature: support Russian language 'ru-RU'

### ISSUE THREAD

**Issue by rassimjhan** [schedule-x/schedule-x#158]
**Is your feature request related to a problem? Please describe.**
Currently Schedule-X doesn't support Russian language.

**Describe the solution you'd like**
I want to add Russian translation into Schedule-X (packages/translations/src/locales/ru-RU)

**Additional context**
I have cloned project and use another language locale for a example. It's clear.

**Comment by tomosterlund** [comment]
**Thanks! For documentation purposes, here my answer for the same question on Discord:**

There's a quick guide on how to contribute here: https://github.com/schedule-x/schedule-x/blob/main/.github/contributing.md#developing

If the step with husky does not work, try either to "npm i -g husky" first, or just skip the husky install step completely.

**Comment by tomosterlund** [comment]
Released as version `1.9.0` 🎉
