### ISSUE TITLE
feature: support Japanese language 'ja-JP' 

### ISSUE THREAD

**Issue by mmzspr** [schedule-x/schedule-x#161]
**Is your feature request related to a problem? Please describe.**
It does not support the Japanese locale.

**Describe the solution you'd like**
I would like to add Japanese translation support.

**Additional context**
This is a fantastic project, and I eagerly hope that it will also extend to the Japanese community. Thank you.

**Comment by tomosterlund** [comment]
Hi! Thank you for your interest in the project, and for opening this issue.

Interest has grown rapidly over the last 2 weeks, and I therefore have a lot of things in my backlog right now. If you (or anyone reading this) want to speed up the translation into Japanese, you can open a PR here, adding a `ja-JP` directory in https://github.com/schedule-x/schedule-x/tree/main/packages/translations/src/locales, and I'll be happy to review it 😊

Info on how to set up the project and contribute is found here: https://github.com/schedule-x/schedule-x/blob/main/.github/contributing.md
