### ISSUE TITLE
feature: set in event "Title" - "date start - date end" If "Title" is empty (in view Month)

### ISSUE THREAD

**Issue by rassimjhan** [schedule-x/schedule-x#167]
**Is your feature request related to a problem? Please describe.**
Right now if event "**Title**" is empty it will look like this:
<img width="1140" alt="titleEmpty" src="https://github.com/schedule-x/schedule-x/assets/63673193/2b09f422-81d5-410e-a591-18c367b95c9f">

**Describe the solution you'd like**
Set in event "**Title**" - "date start - date end" If Title is empty (in view Month)
Like in the picture bellow:
<img width="1138" alt="titleMonth" src="https://github.com/schedule-x/schedule-x/assets/63673193/140b4321-95c2-407f-9857-1349fb0f02a1">

**Additional context**
If I will use custom event "**Title**" (date start - date end) in "**Week**" or "**Day**" view it will look like in picture bellow, Time duplicated:
<img width="361" alt="weekView" src="https://github.com/schedule-x/schedule-x/assets/63673193/c91da14c-b434-4aa3-a33c-5344e2c037b0">

**Comment by Artenio** [comment]
it's a nice idea as improvement

**Comment by tomosterlund** [comment]
Thanks @rassimjhan for opening this.

I'm thinking of aligning with the Google Calendar behavior for this. There, the start time is displayed unless it's a full day event. And when there is no title, there is a placeholder saying "(No title)". Will mark this as v2, since it will mean a breaking change the UI of month view and the date grid of week views.

**Comment by rassimjhan** [comment]
> Thanks @rassimjhan for opening this.
> 
> I'm thinking of aligning with the Google Calendar behavior for this. There, the start time is displayed unless it's a full day event. And when there is no title, there is a placeholder saying "(No title)". Will mark this as v2, since it will mean a breaking change the UI of month view and the date grid of week views.

@tomosterlund could you also add props or something in situations If "title" doesn't need? E.g. :show-title="false"

**Comment by tomosterlund** [comment]
@rassimjhan You can still reuse all the HTML structures and classes from the default event, but you have to code them into your custom event. Would this solve your problem?

About the suggested `show-title` config option: The title is optional so it doesn't need to be hidden, you can just skip entering a title. If this is still only a problem in the date-grid or month-grid, then I do get the problem though. There, the title is still optional, but no time is displayed if you leave it out.

Anyhow, let me know if the first suggestion above solves your problem (using similar HTML and the same styles as the default events)

**Comment by tomosterlund** [comment]
In v2, which will be released soon, the start time of an event will also be displayed in month view.

In case there is no time and no title, there will still not be any content in the default event. However, there is now the `_customContent.monthGrid` with which one can customize the content of the default month event
