### ISSUE TITLE
[feature]: Highlight current time in day/week view

### ISSUE THREAD

**Issue by ayushanand18** [schedule-x/schedule-x#175]
**Is your feature request related to a problem? Please describe.**
Every modern calendar app brings to focus the current time on page load and also highlights the current time by a dotted/dashed line. It would be a great thing to include in this library too. It would remove any unnecessary confusions and reduce the time to look over important events (of course we shouldn't be looking at past events more often than future :) )

**Describe the solution you'd like**
Something how Google Calendar also shows up current time by a horizontal line. 
![image](https://github.com/schedule-x/schedule-x/assets/36472216/b01884c0-a5f2-4b58-ac3b-fc68016fce0a)

Thanks!

**Comment by tomosterlund** [comment]
Thanks for opening this issue. This definitely makes sense to build, so I added it to the project backlog 😊

**Comment by tomosterlund** [comment]
This can now be downloaded with:
`npm i schedule-x/current-time`
