### ISSUE TITLE
feature: support Korean language 'ko-KR'

### ISSUE THREAD

**Issue by composite** [schedule-x/schedule-x#178]
Is your feature request related to a problem? Please describe.
Currently Schedule-X doesn't support Korean language.

Describe the solution you'd like
I want to add Korean translation into Schedule-X (packages/translations/src/locales/ko-KR)

Additional context
I have cloned great project and use another language locale for a example.

**Comment by tomosterlund** [comment]
Hi! Thanks for opening this issue. Been happy to see so many Korean developers discover the library over the last week.

Feel free to open a PR, after forking this repo and adding the translations to a feature branch. There is a quick setup guide here: https://github.com/schedule-x/schedule-x/blob/main/.github/contributing.md#developing

And if you want to have a look at another PR for how to add a language, here is an example: https://github.com/schedule-x/schedule-x/pull/165/files
