### ISSUE TITLE
Date Field Calendar Issue

### ISSUE THREAD

**Issue by caturandi-labs** [schedule-x/schedule-x#210]
**Context:**

- Browser: All browser
- Browser-version : All version
- Schedule-X : Vue version, v1.7.0

**Describe the bug**

If we have input field  (checkbox, text, number) in the same screen , the date field from calendar section will auto binding from that input field value (refer screenshot). It happened also in the documentation website.

**To Reproduce**

1. Create calendar
2. Create input field in the same page/screen
3. Text something in the input field
4. See the date field in the calendar , the value will be bind from the input text field.

**Screenshots**

<img width="1431" alt="Screenshot 2024-02-02 at 11 12 52" src="https://github.com/schedule-x/schedule-x/assets/18569844/b81aff75-7a3b-4148-9c4e-78d6135df91a">

**Comment by tomosterlund** [comment]
Woah! That is not good.

Thanks for opening this issue. I'm on it.

**Comment by tomosterlund** [comment]
Released as version `1.12.2`. Thanks again for opening this issue :)

**Comment by caturandi-labs** [comment]
Thanks a lot, tested and works :)
