### ISSUE TITLE
feature: event modal on hover

### ISSUE THREAD

**Issue by rassimjhan** [schedule-x/schedule-x#228]
**Is your feature request related to a problem? Please describe.**
I found event modal, but it's trigger on click. It would be nice also trigger on **hover**.

**Describe the solution you'd like**

> Write a plugin for achieving this. We would need to expose the ids of each event on their wrapping elements, and then from the plugin you could add event listeners like eventElement.addEventListener('mouseover', ...) @tomosterlund 

**Additional context**

> I think exposing the event id on the element wrapper would be a good idea anyway, for a variety of use cases and future plugins. @tomosterlund

**Comment by tomosterlund** [comment]
Hi @rassimjhan. 

I think this is a feature that could make sense. The only thing I want to prevent is building a bunch of extra logic into the core library for this. Currently I have the following problem, that the drag and drop makes the event-modal go a bit crazy when I allow to open it on the `onmouseenter` event.

https://github.com/schedule-x/schedule-x/assets/63011648/69631819-e3f1-40b2-a09c-dde3b053e0db

I'm sure there are ways to fix this. It just can't become a 100-line fix full of if-else statements, for such a tiny piece of functionality. If anyone wants to try it out and can make it happen, I'd love to welcome this into the library.

The alternative is of course we just go ahead and expose the ids of all events on their respective wrapper elements, then anyone could build their own plugin for this feature.

**Comment by tomosterlund** [comment]
I would be open to pull requests for this feature, but will close it for now since no one is working on it.

Anyone wanting to implement this can open another issue and link to this.
