### ISSUE TITLE
Mobile Calendar Scrolling on Event Doesn't Work

### ISSUE THREAD

**Issue by kodyVS** [schedule-x/schedule-x#229]
When in mobile view, when scrolling the calendar, you cannot start the finger press on an event. Since the event on day-view takes up most of the screen, it makes the user think the calendar is broken. 

**To Reproduce**
1. View the calendar in mobile mode. 
2. Scroll down on an event.

**Expected behavior**
Able to scroll the calendar from anywhere inside the calendar. 

**Screenshots**
![image](https://github.com/schedule-x/schedule-x/assets/59428387/f21498d0-90a8-4063-8bc1-f404eac48fb6)

**Comment by tomosterlund** [comment]
Thanks for reporting this. To me, this makes a lot of sense to fix, but only given that you do not have the drag-and-drop plugin installed. I would propose the following acceptance criteria:

1. On touch device with drag & drop plugin: `touchstart` on calendar event => start dragging. Grid does not scroll in the opposite direction on `touchmove` which would be the default behavior.
2. On touch device without drag & drop plugin: `touchstart` => scroll the grid on following `touchmove` events.

**Comment by tomosterlund** [comment]
@kodyVS I had a real tough one with this. I opened a PR but do not feel very confident merging this without a second pair of eyes on it.

Would you like to:
1. Have a look on the acceptance criteria above, whether they make sense?
2. Check out the branch from the PR and test if the criteria are actually met by the changes.

Would appreciate any help on this :)

**Comment by kodyVS** [comment]
Hey Tom, this now works well for when the drag-and-drop plug-in is not active. 

With the drag-and-drop plug active, I think a more intuitive approach would be: 

Long finger press = Move the event around
`touchstart` = Open the modal. 
`touchmove` = Scroll the calendar. 

and keep that `touchmove` at the bottom of the event resizes the event.
