### ISSUE TITLE
[Question] Possible to remove events when viewing event

### ISSUE THREAD

**Issue by GitTheCodeAndHitTheRoad** [schedule-x/schedule-x#234]
Would it be possible to include functionality to remove events afer opening/viewing them? 

For example if I would like to add a "remove" button to the events which triggers the deletion. For this the object ID would need to be known by the custom remove() function, also to remove events from the backend.
![image](https://github.com/schedule-x/schedule-x/assets/54642786/d03fb683-903c-436f-a248-addb2c299244)

**Comment by tomosterlund** [comment]
Hey there. First of all thanks for taking interest in improving this library 😊 

Here's a part of an answer to an almost identical question on Discord from the other day:

> ...
> there is also a task in the project backlog, for enabling the usage of a custom component in the event-modal:
> https://github.com/orgs/schedule-x/projects/3. With a custom component injected in the place of the modal, you could
> implement a trash button, edit button or anything else related to updating events.

Basically, there are so many different use cases one could want to implement in a modal like that. What I want to avoid is having every single one of them flow into the library, and instead offer stronger customization options, like being able to define the content of the modal 100%. So it's in the pipeline of being made possible, just a little differently to how you would picture it.

**Comment by tomosterlund** [comment]
But since it's a great question, and we've had twice in a couple of days now, I would suggest we leave this issue open until the custom component feature for the event modal has been implemented.

**Comment by GitTheCodeAndHitTheRoad** [comment]
Great to hear and thanks for the quick response! In the mean time I found your other project Qalendar which already has this feature and it works great

**Comment by tomosterlund** [comment]
Now a custom component for the event modal is available: https://schedule-x.dev/docs/calendar/vue & https://schedule-x.dev/docs/calendar/react

Glad to hear you like Qalendar 😊 Just bear in mind: that project is not in development anymore, merely maintained for bugs and dependency updates.
