### ISSUE TITLE
Set a list of events after the first initialisation

### ISSUE THREAD

**Issue by aspitrine** [schedule-x/schedule-x#268]
**Is your feature request related to a problem? Please describe.**  
I have some calendars loaded in relation to the calendar date selection. 
But i can't add or remove calendar programmaticaly.
And i can't replace all events set to another. (remove without know the ids)

**Describe the solution you'd like**  
An API to set a list of events / calendars like this

```ts
const calendarData = createCalendar({
  views: [viewMonthGrid, viewMonthAgenda, viewDay, viewWeek],
  defaultView: viewMonthGrid.name,
  isDark: isDark.value,
  locale: locale.value,
  events: [],
  calendars: {}
})

// set a list of events (remove all previous events, and add all new)
calendarData.events.set([{...}, {...}]);
// set a list of calendars (remove all previous calendar, and add all new)
calendarData.calendars.set({
    personal: {
      colorName: 'personal',
      lightColors: {
        main: '#f9d71c',
        container: '#fff5aa',
        onContainer: '#594800',
      },
      darkColors: {
        main: '#fff5c0',
        onContainer: '#fff5de',
        container: '#a29742',
      },
    },
    work: {
      colorName: 'work',
      lightColors: {
        main: '#f91c45',
        container: '#ffd2dc',
        onContainer: '#59000d',
      },
      darkColors: {
        main: '#ffc0cc',
        onContainer: '#ffdee6',
        container: '#a24258',
      },
    })
```

Thank's for this amazing lib, i love it !

**Comment by tomosterlund** [comment]
Hey there. Thanks for opening this issue, and for the appreciation too 😊

I think the `calendar.events.set` API makes perfect sense to integrate into the library. Should also be a fairly small feature to build. If anyone beats me to it, it can be implemented like this:

1) edit interface in `packages/shared/src/utils/stateful/events-facade/events-facade.interface.ts`
2) implement method in both classes that implement this interface

For the suggested `calendars.set` API, you could achieve this through writing your own plugin. Here the docs for writing plugins: https://schedule-x.dev/docs/calendar/plugins/custom-plugins. Probably it could look something like this (non-tested code, just jotted it down here in the GitHub editor):

```ts
import { CalendarAppSingleton } from '@schedule-x/shared'

class ConfigUpdaterPlugin {
  name = 'config-updater-plugin'
  $app!: CalendarAppSingleton
 
  init($app: CalendarAppSingleton) {
    this.$app = $app
  }

  setCalendars(calendars) {
    $app.config.calendars = calendars
    // if you need all events to update reactively upon this, you might need to add this.$app.calendarEvents.list.value = [...this.$app.calendarEvents.list.value]
  }
}
```

**Comment by aspitrine** [comment]
I have done something like this

```ts
class ConfigUpdaterPlugin {
  name = 'config-updater-plugin'
  $app!: CalendarAppSingleton

  init($app: CalendarAppSingleton) {
    this.$app = $app
  }

  setCalendars(calendars: CalendarConfig['calendars']) {
    this.$app.config.calendars = calendars
    this.$app.calendarEvents.list.value = [...this.$app.calendarEvents.list.value]
  }
}

const configUpdaterPlugin = new ConfigUpdaterPlugin()
```

and 

```ts
watch(props, () => {
  configUpdaterPlugin.setCalendars(props.calendars)

  props.events?.forEach((event) => {
    if (calendarData.events.get(event.id))
      calendarData.events.update(event)
    else
      calendarData.events.add(event)
  })
})
```

Event was added and when console log calendarData (`calendarData.$app.config.calendars`), calendars are set with the color, but all the events displayed was without color. (in `calendarData.$app.calendarEvents.list.value`, i have props `_color` set correctly)

**Comment by tomosterlund** [comment]
Oh sorry, realized now that I saw your reply that there is an obstacle for this to work:

though many config options have no non-reactive side effects triggered on initialization, `calendars` does. There is an internal class `EventColors`, responsible for setting some custom CSS properties, which is instantiated upon creating the calendar. Changing the `calendars` option afterwards does not instantiate this `EventColors` class again. This could of course be modified, but would require a bit of refactoring and overhead of code. How many different calendars do you use?

1) Would it be too much to just load them all upon initializing the calendar?
2) If yes: it sounds like the best option would be to re-render the calendar component upon loading additional calendars. Since it looks like you're using Vue, you could just set a `:key` prop and change the value of this prop when you load new calendars.

Let me know if this solves your problem. The `events.set` API I'd still implement no matter what.

**Comment by aspitrine** [comment]
Ok, i see the problem.

I have user who can create type of meeting (it’s like a calendar but with more options)
They can invité other people who they dont have access a the calendar and just for this date they can access.

So i load calendar for specific date range (and show toggle for activate or not this calendar)

i dont have access to all calendars at the initialisation.
The issue with the key is the current date.
I have already try but a lot of bug when change the month and load new date for the range.

i will deep dive in the lib more around the EventColor to find a workaround.

**Comment by tomosterlund** [comment]
"The issue with the key is the current date. "

Do you mean that the current date set by the user goes lost? In this case, I think it would make perfect sense to also expose a way of getting the current date. It was also suggested in Discord a few days back that there should be an API for getting the name of the view. I think the calendar-controls plugin should maybe be extended with `getView` and `getDate`.

**Comment by aspitrine** [comment]
I don't store the current date. I have explore a little with it but the solution with the `:key` was more like an hack and i don't like it. It could work but refresh all the calendar was... A little to much if i can avoid it.

I prefer find an other way and use it in last resort :) 

Thanks for all your response !

**Comment by tomosterlund** [comment]
Hm, I'll look into how big of a code overhead it would be to make `config.calendars` reactive. This discussion makes me think maybe I should have made the whole config object reactive in the first place, since I'm exposing it via the `$app` API for plugins.

Let me get back to you on this when I've had a closer look :)

**Comment by aspitrine** [comment]
Thanks a lot ! 

If it's possible to make the config object reactive, this can be really great with a lot of freedom ! =D

Good luck for your closer look 💪🏻

**Comment by tomosterlund** [comment]
In @schedule-x/calendar v1.25.0 the `events.set` API has been added, and the `config.calendars` object has been turned into a reactive signal, whose `value` property you can now override in a plugin :) 

There's a test case showcasing how you might apply this: https://github.com/schedule-x/schedule-x/blob/main/packages/calendar/src/components/__test__/override-config.spec.tsx

**Comment by tomosterlund** [comment]
Thanks again for contributing with this issue!

**Comment by aspitrine** [comment]
Perfect!
Thanks a lot, i will try it !

good luck for the v2! 💪🏻
