### ISSUE TITLE
Configurable intervals (or special hours)

### ISSUE THREAD

**Issue by tomosterlund** [schedule-x/schedule-x#274]
On a side note, probably the "working hours" use case is highlighting a missing feature that is present, for instance on vue-cal (https://antoniandre.github.io/vue-cal/#ex--special-hours) 
Special hours aren't events as such but reference areas in the timeline that are shown in the background.
Just saying.

_Originally posted by @cleverplatypus in https://github.com/schedule-x/schedule-x/issues/264#issuecomment-1970100710_

**Comment by Revadike** [comment]
Yeah could be great for indicating when you're (un)available.

**Comment by tomosterlund** [comment]
Reference to an idea for how to implement this, as so-called background events: https://github.com/schedule-x/schedule-x/issues/405#issuecomment-2094591561
