### ISSUE TITLE
feature: support Brazilian Portuguese language 'pt-BR'

### ISSUE THREAD

**Issue by henriquevschroeder** [schedule-x/schedule-x#278]
**Is your feature request related to a problem? Please describe.**  
Brazilian Portuguese translation is not available.

**Describe the solution you'd like**  
I would like to add Brazilian Portuguese translation support.

**Additional context**  
I really like this project and want to extend it to Brazilian users.

**Comment by tomosterlund** [comment]
Thanks for your contribution. I'll push a release later tonight :)
