### ISSUE TITLE
feature: support Dutch language 'nl-NL'

### ISSUE THREAD

**Issue by YannickWhorst** [schedule-x/schedule-x#280]
**Is your feature request related to a problem? Please describe.**  
The Dutch translation for schedule-x is currently not available.

**Describe the solution you'd like** 
I would like to see the Dutch translation added to the calendar and date-picker.

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this feature
- [X] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
Hey @YannickWhorst thanks for opening this. Don't worry about the formatting unless you formatted that line in the spanish translations yourself. Minor updates in the prettier-library could also cause stuff like that, which is OK.

**Comment by tomosterlund** [comment]
Thanks for your contribution. I'll push a release later tonight :)
