### ISSUE TITLE
How to let the schedule block resizable in Vue's version

### ISSUE THREAD

**Issue by dang0705** [schedule-x/schedule-x#286]
I download the Vue demo and update all the dependencies with latest version(1.22.0),but it seems not available to resize the schedule block. 
So is there any configurations that I should set or this feature isn't inplement yet in Vuejs version?

**Comment by tomosterlund** [comment]
Hi @dang0705. What do you mean by _schedule block_? All resizing functionality that works in native JS version should also work in Vue. Could you share your code here?

**Comment by tomosterlund** [comment]
Closed due to inactivity. You can join the Discord chat for any questions on how to use the library :) 

https://discord.gg/yHbT3C4M8w
