### ISSUE TITLE
Expose Exernal interface

### ISSUE THREAD

**Issue by aspitrine** [schedule-x/schedule-x#301]
I want to type a params with the type `CalendarEventExternal`, but not available externally.

Possible to export all `External` type ? 

A workaround was to do :
```ts
export type CalendarEventExternal = NonNullable<Parameters<typeof createCalendar>[0]['events']>[number]
```

So it's not urgent.

Thanks 🙏

**Comment by tomosterlund** [comment]
This is now featured in the latest version of @schedule-x/calendar. React and Vue releases follow in short
