### ISSUE TITLE
Customization of Event Modal

### ISSUE THREAD

**Issue by jjgrayg** [schedule-x/schedule-x#308]
Is there any way at all to customize the event modal to, for example, include a link or other additional information? The documentation mentions an `eventModal` slot for Vue-based applications but this slot seems to do nothing at all and I can't find any other documentation to suggest how I should go about this.

I am trying to use this library to present a calendar of upcoming shipments for a returns management system I am writing, and it works absolutely phenomenally for the most part and has been extremely well received by the people who will be using my system. The caveat is they'd like a way to click on the event in the calendar and be able go to the detailed page for whatever shipment they are looking at. The most obvious solution would be to simply override the working `monthAgenda` and `dateGridEvent` slots with components that redirect on click, however the event modal does provide additional useful information about each event, so if there were simply a way to modify the `eventModal` or replace it with a custom event modal that could include a link that would be the best outcome.

Any help on this is greatly appreciated!

**Comment by tomosterlund** [comment]
Hey there.

The feature is documented here: https://schedule-x.dev/docs/calendar/vue#slots--custom-components. On that page you will also find an example of how to use the slot props. I'm not sure how to extend this though, without going into details about how Vue slots work.

Though not meant for documentation purposes, you could also have a look into this file for an example of the eventModal slot: https://github.com/schedule-x/vue/blob/main/development/App.vue

I'll close this, but you can also join the chat on Discord if you need further help with this :)
