### ISSUE TITLE
[feature]: Color Saturday and Sunday

### ISSUE THREAD

**Issue by reinsp5** [schedule-x/schedule-x#309]
**Is your feature request related to a problem? Please describe.**  
All days of the week are shown in the same color, but most actual calendars have colors for Saturday and Sunday.

**Describe the solution you'd like**  
The `Month*` view has a `data-date` attribute, but the other views do not.
Also, it might be nice to have a CSS class for each day of the week, in case you want to color all of a particular day of the week at once. 
`ex: class="sx__sunday"`

**Additional context**  
![image](https://github.com/schedule-x/schedule-x/assets/26256090/c3a01850-395b-4689-968d-39b13f0b6052)

**Comment by tomosterlund** [comment]
Thanks!

I think it could then be implemented like this.

Elements with the following classes
**sx__week-grid__date**
**sx__time-grid-day**
**sx__month-grid-day**
**sx__month-agenda-day**

will always be accompanied by a class for the weekday, like **sx__monday**, **sx__tuesday** etc

**Comment by reinsp5** [comment]
Thanks, tomosterlund!

I think that's a good idea too. I think it would be useful to have a dedicated class for each day of the week to apply the style all together.
