### ISSUE TITLE
Config -> calendars object, Nuxt3

### ISSUE THREAD

**Issue by dbaranec** [schedule-x/schedule-x#311]
**package.json**

         "dependencies": {
             "@preact/signals": "^1.2.3",
             "@schedule-x/calendar": "^1.25.0",
             "@schedule-x/drag-and-drop": "^1.25.0",
             "@schedule-x/event-modal": "^1.25.0",
             "@schedule-x/theme-default": "^1.25.0",
             "@schedule-x/vue": "^1.21.0",
             "@typescript-eslint/parser": "^7.3.1",
             "axios": "1.6.8",
             "preact": "^10.20.1"
          }
 i get error after i add calendars object into configuration, this is my component 

![Screenshot 2024-03-27 at 16 12 05](https://github.com/schedule-x/schedule-x/assets/9531549/2625a2cd-4fab-4a6b-a33d-febae04dfa4a)

after refresh i got

![Screenshot 2024-03-27 at 15 57 37](https://github.com/schedule-x/schedule-x/assets/9531549/fd661987-410a-4f8c-ac6d-01073adbfdc5)

**Comment by dbaranec** [comment]
in index.vue i need to wrap it again to ClientOnly

` <ClientOnly>
                    <AppCalendar />
                </ClientOnly>`

**Comment by tomosterlund** [comment]
Glad you solved it. Probably you don’t need the ClientOnly tag in the AppCalendar component, but only in the wrapping component

**Comment by dbaranec** [comment]
right
