### ISSUE TITLE
Template slot error on destroy.

### ISSUE THREAD

**Issue by dovepa** [schedule-x/schedule-x#314]
Hello,

I've encountered an interesting bug while using Vue 3. When utilizing slots within my component, I noticed that upon destroying the component, I encounter a callback named onRangeUpdate. At this point of destruction, an error related to template slots occurs. It seems like the component is attempting to import destroyed <template> elements. Has anyone else encountered a similar issue?
Notably, this bug only manifests when an event is visible at the moment of destruction.

ex :
![image](https://github.com/schedule-x/schedule-x/assets/33008055/a1b40a0f-ff20-40ee-a98c-f9865dad43e7)

Steps to Reproduce:

Implement a component with slots.
Destroy the component.
Observe the error related to template slots.
Expected Behavior:

The component should be destroyed gracefully without any errors related to template slots.

Actual Behavior:

An error occurs when destroying the component, indicating issues with template slots.

![Screenshot 2024-03-28 143717](https://github.com/schedule-x/schedule-x/assets/33008055/3b12c159-56c9-49d6-85bd-e481e89132de)
![Screenshot 2024-03-28 143547](https://github.com/schedule-x/schedule-x/assets/33008055/224b957c-c41d-48a5-988d-be77e85acdaf)

**Comment by dovepa** [comment]
I also couldn't reproduce the bug in a demo environment. However, adding '?' as shown in the code below fixed my issue.

` setCustomComponentMeta(e) {
      const t = [...this.customComponentsMeta], o = e.wrapperElement?.dataset.ccid, n = t.find(({ wrapperElement: m }) => m?.dataset.ccid === o);
      n && t.splice(t.indexOf(n), 1), this.customComponentsMeta = [...t, e];
    }`

**Comment by dovepa** [comment]
Do you have any idea about the origin of the bug?

**Comment by dovepa** [comment]
Alright, I've figured out how to reproduce the bug directly with the demo.

![image](https://github.com/schedule-x/schedule-x/assets/33008055/44cd5406-7999-4d21-b4fa-9a01ee71c3cc)

Here's the code for app.vue:

```
<script setup lang="ts">
import { ScheduleXCalendar } from '@schedule-x/vue'
import {
  createCalendar,
  viewDay,
  viewWeek,
  viewMonthGrid,
} from '@schedule-x/calendar'
import '@schedule-x/theme-default/dist/index.css'
import { createEventModalPlugin } from '@schedule-x/event-modal'
import { createDragAndDropPlugin } from '@schedule-x/drag-and-drop'
import CustomTimeGridEvent from "./components/CustomTimeGridEvent.vue";
import {useEventsStore} from "./store/events-store.ts";
import { ref } from 'vue'

const calendarApp = createCalendar({
  selectedDate: '2023-12-19',
  locale: 'en-UK',
  views: [viewDay, viewWeek, viewMonthGrid],
  defaultView: viewWeek.name,
  firstDayOfWeek: 0,
  plugins: [createEventModalPlugin(), createDragAndDropPlugin()],
  events: [
    {
      id: 1,
      title: 'Event 1',
      start: '2023-12-19',
      end: '2023-12-19',
    },
    {
      id: 2,
      title: 'Event 2',
      start: '2023-12-20 12:00',
      end: '2023-12-20 13:00',
    },
    {
      id: 3,
      title: 'Event 3',
      start: '2023-12-20 04:00',
      end: '2023-12-20 08:10',
    },
  ],
})

const customComponents = {
  timeGridEvent: CustomTimeGridEvent,
  // dateGridEvent: CustomDateGridEvent,
}

const eventsStore = useEventsStore()
  const testbug = () => {
    let container = document.getElementById('calendarContainer')
    calendarApp.render(container as HTMLElement)
  }
</script>

<template>
   <div id="calendarContainer">

    Selected events: {{ eventsStore.chosenEvents.map(e => e.id) }}

    <ScheduleXCalendar
        :calendar-app="calendarApp"
        :custom-components="customComponents"
    >
      <template #dateGridEvent="{ calendarEvent }">
        <div :style="{ backgroundColor: 'green', color: 'white', width: '100%', height: '100%' }">
          {{ calendarEvent.title }} test here
          <input type="checkbox" @change="testbug()">
        </div>
      </template>
    </ScheduleXCalendar>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
```

How to reproduce the bug:

https://github.com/schedule-x/schedule-x/assets/33008055/4ba04e40-8ca9-49bb-9b3a-fcda6c09dfe6

**Comment by tomosterlund** [comment]
In this function:

```
const testbug = () => {
    let container = document.getElementById('calendarContainer')
    calendarApp.render(container as HTMLElement)
  }
```

You are creating a new calendar instance and trying to mount it into an element that you created yourself. This is not a supported way of working the Vue component, because

1) the Vue component creates its own wrapping element `.sx-vue-calendar-wrapper` 
2) the component uses this element as argument for the `render` method.

If you're creating your own wrapping element and are calling `render`, that might be what's causing the error. Are you calling the `render` method in your application too?

**Comment by dovepa** [comment]
Hello,

Thank you for your response.

Indeed, I'm using a container for my calendar:
`<div class='customContainer'><calendar....></div>`

I'm not using the render method. 
Once the custom container is removed, I no longer have the bug.

Thank you for your help. I'll close the bug.
