### ISSUE TITLE
feature: support Turkish language 'tr-TR'

### ISSUE THREAD

**Issue by byhipernova** [schedule-x/schedule-x#335]
**Is your feature request related to a problem? Please describe.**  
The Turkish translation for schedule-x is currently not available.

**Describe the solution you'd like**  
I would like to see the Turkish translation added to the calendar and date-picker.

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this feature
- [x] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
Released as @schedule-x/calendar 1.30.0. Releases for the Vue and React components will follow once Renovate Bot gets to it.

Thanks again 🚀
