### ISSUE TITLE
Configure displayed event fields in calendar view

### ISSUE THREAD

**Issue by afrancesm** [schedule-x/schedule-x#348]
Hello! As suggested on Discord, I'm opening this issue to contribute an idea.

Currently the event view in the time-grid only displays limited information, such as people's names. It would be beneficial to have the ability to configure which fields are shown in this view, such as location or description.

![scheduler](https://github.com/schedule-x/schedule-x/assets/2932506/c7dcc3c0-9ac5-4493-a7cc-f82214a3b14a)

**Proposed Solution:** Implement a configuration option that allows users to select which fields they want to display in the event view.

**Comment by tomosterlund** [comment]
As of v2, due for release in the next couple of weeks, location will be displayed by default.

For customizing even further, one can use custom components, or the `_customContent` property of an event

Thanks for the suggestion though!
