### ISSUE TITLE
MomentJS adapter 

### ISSUE THREAD

**Issue by babdikaarov** [schedule-x/schedule-x#351]
**Is your feature request related to a problem? Please describe.**  
Kyrgyz language is not supported in Chrome for translating Months and Weeks which are handled by browser
could be great if we can opt the translations to momentjs if there is a problem with language implementations

**Describe the solution you'd like**  
An adapter and some config options to let this adapter to handle the translations of weeks and months
momentJs has also a way to implement your own names for months and weeks

**Things that could speed up the process**
- [ x] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by justin-hackin** [comment]
MomentJS is a 😵 project, see https://momentjs.com/docs/#/-project-status/

**Comment by vukadinFE** [comment]
> MomentJS is a 😵 project, see https://momentjs.com/docs/#/-project-status/

Yeah. dayjs and date-fns replaced it

**Comment by tomosterlund** [comment]
I think for now I'll go ahead and close this issue. I'd be open to a PR for this, but don't think I will build this in the near future.

If anyone wants to build this, just let me know and we can have a chat about it
