### ISSUE TITLE
ru-RU locale .toLocaleString has output of lowerCase string 

### ISSUE THREAD

**Issue by babdikaarov** [schedule-x/schedule-x#353]
Thank you for wanting to take the time to report a problem. In order to increase the chances of the issue being 
resolved,
please take a moment to give as much relevant information as possible.

**Context:**

- Browser-version
- Schedule-X version [e.g. v1.1.0] Please make sure that you've tried the latest version before reporting the bug.

**Describe the bug**

while using ru-RU locale the months names are in lower case 

**To Reproduce**

1. set locale config to ru-RU
2. execute npm run dev
3. open calendar
4. month name in lower case

**Expected behavior**

the first letter of month in upperCase

**Screenshots**
<img width="248" alt="Screenshot 2024-04-15 at 23 56 05" src="https://github.com/schedule-x/schedule-x/assets/66443735/e94f4157-1698-42c0-8227-21d0498c0a05">

**posible solution**

To resolve the issue i had created a pull request with branch name "upperCaseRuLang"

**Comment by tomosterlund** [comment]
I think this is not the correct approach. From my brief research, it appears Russian, among other languages that Schedule-X supports, does generally **not** capitalize month names. Also I wouldn’t override dates that the native JavaScript APIs spit out.

What we could do is capitalize stand-alone words like in the case of the calendar header, or date picker popup, but then we should do that for all languages.

Does that sound OK?

**Comment by tomosterlund** [comment]
For example, I think we can capitalize these:

![Bildschirmfoto 2024-04-16 um 06 21 15](https://github.com/schedule-x/schedule-x/assets/63011648/45fa5fe7-5684-479c-966d-010613d512b9)
![Bildschirmfoto 2024-04-16 um 06 21 03](https://github.com/schedule-x/schedule-x/assets/63011648/023f912b-8e9c-4392-8298-81266d02ff25)

But not these:
![Bildschirmfoto 2024-04-16 um 06 21 44](https://github.com/schedule-x/schedule-x/assets/63011648/62761758-ea91-40c8-8c09-d03a331b3f29)

**Comment by babdikaarov** [comment]
Yeah @tomosterlund  that works fine with me. Just in case if somebody wants to uppercase it they could just write some css
