### ISSUE TITLE
ky-KG locale has bugs in displaying Month and Weeks name

### ISSUE THREAD

**Issue by babdikaarov** [schedule-x/schedule-x#354]
Thank you for wanting to take the time to report a problem. In order to increase the chances of the issue being 
resolved,
please take a moment to give as much relevant information as possible.

**Context:**

- Browser [chrome, safari, firefox, opera]
- Browser-version
- Schedule-X version [e.g. v1.1.0] Please make sure that you've tried the latest version before reporting the bug.

**Describe the bug**

the ky-KG locale has following problems:
1. no support to output the names of months and weeks in Chromium and Opera
2. Has UI bug SAFARI , FireFox browsers when used ky-KG locale which completly destroys interactivity

the issue for supporting for ky-KG in the Chromium has been submitted [issues.chromium.org](https://issues.chromium.org/issues/334720108)

**To Reproduce**

1. config locale to ky-KG
3. execute npm run dev
4. open calendar on Safari and FireFox the UI will break
5. open calendar on Chromium or Opera the Months and Weeks name will be opted to browser default months weeks names

**Expected behavior**

1. the UI should not break upon using ky-KG
2. the Chromium or Opera update for ky-KG has no clear time when will be implemented

**Screenshots**

if interested in more details I am available on Discord @bekaska

**Comment by tomosterlund** [comment]
Could be solved by solving https://github.com/schedule-x/schedule-x/issues/351
