### ISSUE TITLE
Feat - leading trailing date

### ISSUE THREAD

**Issue by comadaihiep92** [schedule-x/schedule-x#360]
**Is your feature request related to a problem? Please describe.**  
I faced an issue when the user could click a date unrelated to the current month display in the heading so I wanted to hide leading and trailing dates in the calendar in mobile mode.

**Describe the solution you'd like**  
I will add new 2 class names sx__is-leading-date, sx__is-trailing-date suggest by @tomosterlund on discord. It need to handle some logic to show class name and then we can custom style by css 👯 
# sample css custom to hidden base on new class name
`.sx__is-leading-date, .sx__is-trailing-date {
  visibility: hidden;
}`

**Additional context**  
Current:
![Screenshot 2024-04-16 at 17 06 17](https://github.com/schedule-x/schedule-x/assets/14916970/49e9db3e-6d9b-45ba-ab49-1f247cacf0a7)
New uppdate:
![Screenshot 2024-04-16 at 17 01 38](https://github.com/schedule-x/schedule-x/assets/14916970/f77e9018-4d4c-4db5-8d3a-9e10891388c9)

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this feature
- [x] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
Merged, and will be released later this week :) Thanks again for contributing!
