### ISSUE TITLE
Customize weekCalendar row and column headers

### ISSUE THREAD

**Issue by salah-dev** [schedule-x/schedule-x#363]
Hi, 
First, thanks for this wonderful tool.

Is it possible to customize (or change) the weekCalendar columns headers. I use the French local as a config and I would like to display the full name of the day instead of the abbreviation ?

**Example :** Monday is just displayed as "Mon." instead of "Monday" for english locale.
![image](https://github.com/schedule-x/schedule-x/assets/56580898/52500993-a78f-46b6-8ccc-5401df2cdf82)

Is it also possible to customize the row headers (hours, background color) because when I set the boundaries between 7:00 am and midnight for instance, 7:00 is not display (although the slot exists for this hour) ?

**Example :** 
![image](https://github.com/schedule-x/schedule-x/assets/56580898/56d9b7f4-37d8-4e27-949e-5c6332a5fb82)

Thanks and best regards !

**Comment by tomosterlund** [comment]
Hey.

Thanks for opening this issue.

In regards to displaying the full name, I will not build this option into the library at this point. The reason for this, is I'm trying to keep the library core as small as possible. Though I want to allow for customization, I need to find a balance for how granular those customization options will be.

That said, if you really want the full weekday name you could achieve this by means of JavaScript. I won't be changing class names without announcing it as a breaking change in major versions, so targeting for example `sx__week-grid__day-name` should be safe
