### ISSUE TITLE
Quick Fix: Add event.id into wrapping div. 

### ISSUE THREAD

**Issue by btcbobbington** [schedule-x/schedule-x#376]
Hey Tom, 

As per your request on Discord here is my request. 

Please add the `event.id` into the wrapping div for the individual event. I think a `data attr` would be best:

It would be awesome to have a `data` attribute for this. like so: 

`<div class="sx__time-grid-event-inner" data-event-id="EVENT_ID">`

Actually, if it is also possible and not too much hassle, could you also add a `data` attribute for a `uique id`, like so: 

`<div class="sx__time-grid-event-inner" data-event-id="EVENT_ID" data-unique-id="UNIQUE_ID">`. For this, it would be awesome if it came from the event object: 

```  events: [
    {
      id: 1,
      unique_id: H325J-HGF23AS-XC56NB-VCZSD345
      title: 'Event 2',
      start: '2024-04-22 01:00',
      end: '2024-04-22 02:00',
    },
]
```
The benefit to also having this is that should you need to do something with a database, an event-id is more likely to become conflicting (I assume people will make this auto increment). This way allows a definite unique identifier that can be used on the server backend.

**Comment by tomosterlund** [comment]
Will be featured in the next release.

Thanks again for contributing with this issue!
