### ISSUE TITLE
feat Lock events from drag and drop

### ISSUE THREAD

**Issue by glennwilton** [schedule-x/schedule-x#377]
Suggestion: for Drag and Drop, add a method to stop drag and drop from working; for example, I have completed events that I do not want to be moved. Can be added to the event object alternatively, add in a beforeDrag, beforeResize, beforeDateChange, beforeStartChange, beforeEndChange events ... but these would not be able to affect the layout (hide resize div)

Suggestions, a combination or these?
```
       {
          id: 2,
          title: 'Ski trip',
          start: '2023-12-04',
          end: '2023-12-06',
          _options: {
              changeDay: false,           <--------- Disable Drag/Drop changing the day
              changeStart: false,          <-------------- Disable/Enable changing the start time 
              changeEnd: false            <-------------- Disable/Enable resize duration
          }
        },
```

**Comment by tomosterlund** [comment]
Great idea 😊

Would it still fit your needs if the API looked like this?

```
_options: {
  disableDND: false,           <--------- Disable Drag/Drop completely
  disableResize: false,          <-------------- Disable resizing completely
}
```

**Comment by glennwilton** [comment]
Yeah that would also work, Just some way to stop some events being changed.

**Comment by glennwilton** [comment]
Perhaps the _options about be expanded as well , such as add classes names so you can do custom styling

_options: {
  className : "completed", 
}

**Comment by tomosterlund** [comment]
That makes a lot of sense too. Thanks 💪
