### ISSUE TITLE
feat: Enable adding custom content to the events

### ISSUE THREAD

**Issue by glennwilton** [schedule-x/schedule-x#378]
Feature Suggestion. timeGridDay does not allow custom content, add in two props for the event object, contentText which is escaped and contentHTML which is not escaped.

IF you added in the options in the config to hide the title. date and people then would be very easy to turn off the defaults and add in custom HTML for each item, such as pictures, text, icons.

```
       {
          id: 2,
          title: 'Ski trip',
          start: '2023-12-04',
          end: '2023-12-06',
          contentText: 'These here shows on the body under the time',
          contentHTML: 'This is <strong>NOT SAFE</strong> raw HTML <img src="x.png">'
        },
```

**Comment by tomosterlund** [comment]
I've been thinking the same previously, so I'm open to explore this topic. I'm not 100% sure what you mean with this paragraph though:

> IF you added in the options in the config to hide the title. date and people then would be very easy to turn off the defaults and add in custom HTML for each item, such as pictures, text, icons.

**Comment by glennwilton** [comment]
What I mean is for some events you might want the content of the event box to not show title, people or time and just show some custom HTML.

For example, based on my other post, expand options to hide Title,People, Time on specific events, then if you used customHTML="xxx" then you get full control of the contents of the event, vs your customHTML or customText just showing under the time.

```
_options:{ 
   showTitle: false,
   showPeople: false,
   showTime: false
}

```
Alternatively customHTML could just automatically hide the title and people etc by overriding the content of the eventbox (cut the rezise still works), so you have to generate that yourself, so it works like a vue slot with less hassles having to generate the entire event youself..

**Comment by tomosterlund** [comment]
Would you expect `contentText` and `contentHTML` to also show up in some way or another in the month view, if you had that view too? Or would you expect different properties for different views? For example:

```
{
       id: 2,
       title: 'Ski trip',
       start: '2023-12-04',
       end: '2023-12-06',
       timeGridContentText: 'These here shows on the body under the time',
       timeGridContentHTML: 'This is <strong>NOT SAFE</strong> raw HTML <img src="x.png">'
       monthGridContentHTML: 'something else'
},
```

**Comment by glennwilton** [comment]
Actually yes, but thinking about it perhaps to make this more future proof make them object

```

event: {
      id: 2,
       title: 'Ski trip',
       start: '2023-12-04',
       end: '2023-12-06',
       timeGrid: {
          content: 'xxxx',
          isHTML: true // render as HTML
      },
      monthGrid:{
         content: 'yyyy'
     }}

```
Then in future its easy to expand and add features to the object, or options etc... just examples below, but you get the idea, keeps the event object clean .... and you can set specific timeGrid options or monthGrid options

```
timeGrid: {
    text: 'xxxx',
    isHTML: true // render as HTML
    className: 'late',
    showTime: false
    showTitle: false,
    dragable: false.
    resize: false
}
```

**Comment by tomosterlund** [comment]
I decided on a slightly different API. I figured if you use custom content, we might as well just render it as HTML in all cases. That way it will cover both simple text content but also HTML.

```ts
export default interface CalendarEventExternal {
  id: EventId
  start: string
  end: string
  title?: string
  people?: string[]
  location?: string
  description?: string
  calendarId?: string

  _customContent?: {
    timeGrid?: string
    dateGrid?: string
    monthGrid?: string
    monthAgenda?: string
  }
  _options?: CalendarEventOptions
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any
}

```
