### ISSUE TITLE
Week range

### ISSUE THREAD

**Issue by Revadike** [schedule-x/schedule-x#379]
I would like to see the addition of a week range configuration option, so we can hide weekends if we wanted to.

**Comment by tomosterlund** [comment]
That's a feature I would like too 👍 

Feel free to suggest an API for the config

**Comment by glennwilton** [comment]
Maybe a callback per day so we can modify each day, add classes etc, so we can then, show, hide or hilight holidays

```

day = {    
    date: '2024-4-3'
    dayOfWeek: 0,  // day of week 0-6
    visible: true,
    name: '',
    className: '',
    style:'', // custom styles such as "background: #a00;"
    events: []  // list of events on this day? could style the day based on events
}


// per day callback
onRenderDay( day ){
  if(day.dayofWeek == 0 || day.dayOfWeek==6){
      day.visible = false;
  }

  if(day.date == '2024-12-25'){
    day.className='holiday';
    day.name = "Christmas Day"
  }

  return day
}


// could also do per hour
onRenderHour(hour){
 ....
 return hour;
}


```

**Comment by glennwilton** [comment]
It would also be nice to set the days of the week

weekGridDays: 7 would show a full week
weekGridDays: 5, if started on a Monday would only show Mon-Fri
weekGridDays: 8 would show next Monday,  given an easy way to drag items into the following week
weekGridDays: 14 would show a custom 2 week view...

Moving forwards and back would still add or subtract 7 says,,,, but you would also set

weekGridStep: 7 Add/Subtract 7 days
weekGridStep: 1 would step by a single day
weekGridStep: 14 would step by 2 weeks..

**Comment by tomosterlund** [comment]
I think the `onRenderDay` could be implemented without problem. I like this one a lot. `weekGridDays` should work too. Great ideas 💡 

The `onRenderHour` will not work that well with how this calendar is built. You can however achieve this more or less with `dayBoundaries`

**Comment by glennwilton** [comment]
Glad you like the suggestions.

I've used that type of callback before where I pass an object to modify to customise the output for a few controls in the past, its a very flexible way to customise a control.

**Comment by Revadike** [comment]
Any ETA?

**Comment by tomosterlund** [comment]
This is next in line of the open source features.

I'll probably get to it within the next couple of weeks, but I'm not 100% on this. Currently working on finishing the first premium features.

I'll accept PRs though, should be a pretty straight forward feature to build

**Comment by tomosterlund** [comment]
I decided to implement this with an `nDays` option in the weekOptions. The `onRenderDay` API is a cool idea, but it doesn't work well with the current drag-and-drop implementation, and I don't want to start adding features that aren't compatible with all plugins.

That said, I'm open to PRs for an `onRenderDay` implementation, as long as drag and drop also works when you decide to omit days in the middle of a week.

Will release this in a moment
