### ISSUE TITLE
Event modal fixed position

### ISSUE THREAD

**Issue by Revadike** [schedule-x/schedule-x#380]
Because of the fixed position of event modals, they will remain on the same position in the window when you scroll the page. Ideally, it should move with the page.

**Comment by tomosterlund** [comment]
Uuuh that's a problem I didn't have on my radar. Makes me think fixed positioning maybe wasn't the right pick after all.

I will look into this

**Comment by Revadike** [comment]
My workaround right now, simply dismisses the model on scroll (plus, I also added a listener for Esc)
