### ISSUE TITLE
FEAT: Snap to increments of x minutes

### ISSUE THREAD

**Issue by glennwilton** [schedule-x/schedule-x#382]
In the config add an option to snap to X minutes.

i.e. snap to 5, 10, or 15-minute intervals. Could be start and end the same or different for each

startInternal: 15 // Snap to 15 minute intervals for the start   
endInterval: 5  // Snap to 5 minute intervals for the end

**Comment by tomosterlund** [comment]
There is currently no way of changing the start without changing the end time. The resize plugin only enables resizing by dragging the end of an event.

However, I could enable the same feature for the resize plugin, as for the drag and drop plugin, where you can configure the interval to be 60, 30 or 15 minutes.

Like this then:

```
createResizePlugin(60)
```

I would then not yet add 10 and 5 minutes. I tried this out, but the internal class `TimeGridEventResizer` would need some optimization for this to look nice. Currently when I allow for such fine granular intervals, the cursor and the event get out of sync while dragging.

**Comment by glennwilton** [comment]
Setting it in createResizePlugin and createDragDrop would work ok.

I currently have some code that updates the Event afterwards, not during the drag. It just snaps after you left go ... It needs polish to work better ...... but works ok..... , Updating while dragging would be nicer.

```

onEventUpdate(updatedEvent) {
            console.log('onEventUpdate', updatedEvent)

            // round start time
            let roundToMinutes = 15;
            let startHour = moment(updatedEvent.start).hour();
            let startMinute = moment(updatedEvent.start).minute();
            let startMinuteRounded = Math.round(startMinute / roundToMinutes) * roundToMinutes;
            let start = moment(updatedEvent.start).hour(startHour).minute(startMinuteRounded)
            updatedEvent.start = start.format('YYYY-MM-DD HH:mm');
            
            // round end time
            let endHour = moment(updatedEvent.end).hour();
            let endMinute = moment(updatedEvent.end).minute();
            let endMinuteRounded = Math.round(endMinute / roundToMinutes) * roundToMinutes;
            let end = moment(updatedEvent.end).hour(endHour).minute(endMinuteRounded);
            
            // end must be min roundToMinutes after start
            if(end.diff(start, 'minutes') < roundToMinutes){
                end = start.clone().add(roundToMinutes, 'minutes');
            }            
            updatedEvent.end = end.format('YYYY-MM-DD HH:mm');
            
            // update rounded time in calendar
            calendarApp.events.update(updatedEvent);


```

**Comment by tomosterlund** [comment]
Now I'm not quite sure anymore. Is the main objective here that you want rounding of events upon dragging/resizing? I.e. 10.12 becomes 10.15 and then 10.30 upon resizing? As opposed to 10.12 becoming 10.27?

That I probably won't support. That seems like something one should round before even adding the event in the first place, if you only want to support rounded quarters

I am working right now though on adding the opportunity to change the interval for resizing into 30 or 60 minute intervals. Will try to release today or tomorrow :)

**Comment by glennwilton** [comment]
yes, both the start and end (duration) snapping to 8:00 and 8:15, 8:30, etc.

Typically when planning I divide the day into 15 minute chunks. (or 10 minutes say) I often don't need any finer grain than that. 

for drag and drop and resize, I found without snapping to the 15 minute chunks, it was easy for events to overlap by 3 minutes. which means some events overlapped each other by 3 minutes, or there was a 6-minute gap between events ... which looks messy.

Snapping ensures events align correctly and avoid overlaps; When I use the calendar it's more about chunking and blocking out time than setting exact start and finish times to the minute

I have a modal popup to edit the event, so If I want to edit the time to something exact, I can do that and then lock the event.

Oh,BTW, Unrelated, but I lock the completed and manually locked events from being moved the same way in the onEventUpdate, When you drag and drop it just reverts back to the last position and does not move

```

   onEventUpdate(updatedEvent) {
            console.log('onEventUpdate', updatedEvent)

            if(updatedEvent.task.Completed || updatedEvent.task.ItemLocked){
                // Move back to original position
                updatedEvent.start = updatedEvent.originalStart;
                updatedEvent.end = updatedEvent.originalEnd;
                calendarApp.events.update(updatedEvent);
                return;
            }




```

**Comment by tomosterlund** [comment]
But this must mean that you are rendering the calendar with events that start or end at for example 11:48 instead of 11:45?

If you just round the events upon rendering the calendar instead, you won't have the problem with 3 minutes overlaps?

**Comment by glennwilton** [comment]
I was having an issue when using the feature template, Githib was going in a login loop and not creating the template,.but it appears fixed now for me.

**Comment by tomosterlund** [comment]
Added the option of configuring the interval. Also fixed the ugly rerendering of all events upon resizing just one.

Docs: https://schedule-x.dev/docs/calendar/plugins/resize

Thanks for opening the issue :)

**Comment by glennwilton** [comment]
Let me know is there is some qa6 I can donate to you

**Comment by tomosterlund** [comment]
Thanks for asking. Really appreciate it :) 

Been thinking of setting up a sponsors option here at GitHub.

Can get back to you when that is set up
