### ISSUE TITLE
Feature: Double click events

### ISSUE THREAD

**Issue by glennwilton** [schedule-x/schedule-x#385]
**Is your feature request related to a problem? Please describe.**  
I am using onClickDateTime to add new events; however, it's easy to click on a blank space and have my code pop up a modal to add an event; it's annoying as I subconsciously click on black spaces.

Would be better if I could double-click on a blank space to add and the same for clicking on events, a double-click to edit 

**Describe the solution you'd like**  
add events for double clicks,

- onDoubleClickDateTime
- onDoubleClickDate
- onEventDoubleClick

 or pass a value/ event value returned from the callback 

- onClickDateTime(dateTime, event) 
- onClickDateTime(dateTime, isDoubleClick) 

**Additional context**  
Nope

**Things that could speed up the process**

Sorry, I'm not familiar with typescript; otherwise, I would submit the updated code as seams straightforward

- [ ] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by glennwilton** [comment]
Also while you're at it, an option to capture right clicks as well...

**Comment by tomosterlund** [comment]
I think the `onDoubleClickDate` and `onDoubleClickDateTime` could be implemented with fairly low effort.

the `onDoubleClickEvent` might be too big of an itch, depending on whether it’ll interfere with how the drag and drop plugin interacts with the calendar package. But I, or whoever implements this, could look into it

**Comment by glennwilton** [comment]
Hi

For the event, I got event Double click working with a vue slot, but still good to have.

Double click on date/time would still be required as there is no slot for this.
