### ISSUE TITLE
No displayed recurring events when using recurrence + custom time grid event (Vue)

### ISSUE THREAD

**Issue by astowny** [schedule-x/schedule-x#389]
**Context:**

- Browser : Firefox
- Browser-version : 125.0.2 (64 bits)
- Schedule-X version : 1.35.0

**Describe the bug**

When I use event-recurrence plugin and a custome slot for time grid event, only the first event of the recurrence is displayed in the calendar.

**To Reproduce**

1. Using schedule-x-vue and event-recurrence
2. Add a custom time grid event component in the code, in the slot or in customComponents properties
3. Go on the interface and add a recurring event
4. See error that only the first recurrence is displayed

**Expected behavior**

All the recurring events should be displayed

**Screenshots**
![2024-04-27_13h04_09](https://github.com/schedule-x/schedule-x/assets/24301264/9d86ac42-406d-42e8-a504-1c7671e5fab5)

**Comment by tomosterlund** [comment]
With which API do you add the event?

when you use the events recurrence package, you should, add, query, update and delete events with the events service plugin, from the @schedule-x/event-recurrence package.

**Comment by astowny** [comment]
I use the event recrurrence plugin, with recurrencePlugin.eventsFacade.add({ id: 'qa+' + Math.random(), title: 'rcurrnt vnt',
    start: '2024-04-24 00:00', end: '2024-04-24 12:00', rrule:
    'FREQ=WEEKLY;COUNT=4;BYDAY=MO,TU,WE,FR,SA,SU', })

**Comment by astowny** [comment]
It's working well when I don't use the custom time grid event slot

**Comment by tomosterlund** [comment]
Thanks 👍 I’ll look into this

**Comment by astowny** [comment]
A mean to correct this is to add the star date to the ccid in the getCCID function for a copy

**Comment by tomosterlund** [comment]
Cool! Thanks for finding the fix :) yea, adding the date to the ccid would make sense then, also for the month view.

Feel free to commit it if you want also
