### ISSUE TITLE
Feature/Bug - Setting date within the same week triggers redraw/animation and triggers onRangeUpdate even though same range

### ISSUE THREAD

**Issue by glennwilton** [schedule-x/schedule-x#390]
**Is your feature request related to a problem? Please describe.**  
When changing from a week view, and switching to day view should the day view be today's date? 

Currently It always switches to Sunday (My start of week) and I need to scroll across to today's events...

**Describe the solution you'd like**  
If the today is in the week view, changing to the day view should display today's events

Suggestion 1 - Option in config

changeToDayStart = 'week'  or 'today'  or 'auto' (Auto will be today unless not in the week then its week start)

Suggestion 2 - Perhaps adding the previous range in the onRangeChange so I can programmatically alter it, or even onRangeChange could accept a return value of a new range?

**Additional context**  

**Things that could speed up the process**

**Comment by tomosterlund** [comment]
Hey there 👋 That's not how it works.

Currently, it always switches to the selected date, and I think that makes more sense than switching to today's date per default. 

https://github.com/schedule-x/schedule-x/assets/63011648/51d7c857-ce47-403f-95e1-fede817354db

**Comment by glennwilton** [comment]
Ok, I did not notice that!!!

I've just been setting selected day to start the week,

I'll see how it works when clicking on an event. I will use calendarControls.setDate() to update it to the events day to change it dynamically. That should solve my issue!!

It might be nice to highlight the selected day, even if setting some class **.sx__week-grid__date--is-selected** so I can add my own css.

![image](https://github.com/schedule-x/schedule-x/assets/6619768/6709bff5-3133-4961-add7-95a8c2220c4e)

**Comment by glennwilton** [comment]
Actually just tried this, but it retriggers the animation as I click around the calendar. 

The entire calendar is updated on every click even if the date is within the same week being displayed.

Can you make it so it does not redraw the entire calendar or trigger the animation if the new setDate is within the existing week range.

**Comment by glennwilton** [comment]
In addition, onRangeUpdate is also being trigged when the range has not changed using setDate()
