### ISSUE TITLE
"Schedule" view

### ISSUE THREAD

**Issue by justin-hackin** [schedule-x/schedule-x#393]
**Is your feature request related to a problem? Please describe.**  

I would like a brief overview of all events in a list. This is useful for both very sparsely populated calendars to prevent excessive pagination advancement and for densely populated calendars where items might be too overlapped to read from a month/week view.

**A clear and concise description of what you want to happen. Preferably with a code example or even the API you would 
like to see.**

Google Calendar has a "Schedule" view which is a list of all events in the near future. The range of events displayed there seems to be about 4 weeks from the currently selected date. 

Consider the option of lazy-loading new content when one reaches the end of the list or providing a pagination interface at the bottom. This could be a `navigationType` option with: `none`, `pagination` and `lazyLoading`.

In google calendar the < and > buttons only advance by 1 day. I don't think this is the most optimal interaction. I would prefer to advance by the period (.e.g. 4 weeks) that the schedule observes. Consider an option to define the range length.

**Additional context**  

[Initiating Discord discussion](https://discord.com/channels/1183076861509632011/1183076861509632014/1233599215347830804)

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
Awesome 👏  Thank you once again for a detailed issue.

I love the `navigationType` idea. A `rangeLength` option with values like `week` and `month` would also make sense for the paginated version
