### ISSUE TITLE
Does not appear to be a way to get the selected Date or an event when selected Date changes?

### ISSUE THREAD

**Issue by glennwilton** [schedule-x/schedule-x#397]
**Is your feature request related to a problem? Please describe.**  
Does not appear to be a way to get the selected Date, Also no event when selectedDate changes? 

**Describe the solution you'd like**  
calendarControls.getDate() returns the selected date

add event onSelectedDateUpdate() which will trigger even if onRangeUpdate does not. ** With recent update onRangeUpdate will not trigger if range is the same

**Comment by tomosterlund** [comment]
Thanks :)

`calendarControls.getDate()` makes sense to me as is ✅
`onSelectedDateUpdate` can you help me understand your use case? I decided against this on building v1, because my prediction was that people would only care about when the range changes, because this affects which events you would like to show.

**Comment by glennwilton** [comment]
Sorry I was wanting a GetDate not setdate, to get the date selected

I have a job list next to the Callander, and when someone clicks add button
on the job or multiple jobs, I want to pop up a modal with the job details
pre populated for the event, and set the date to the selected date in the
Callander, so I need to know the selected date.

In future it would be good to hilught the selected day, I've already put in
an issue for this.


OnSelectedDateUpdate would be good because I keep track of the selected
date and update all 3 Calanders on the same page.

Without that they get out of sync

**Comment by tomosterlund** [comment]
That all makes sense.

Also, cool that you're using multiple calendars on one page. Is that working out fine so far?

**Comment by tomosterlund** [comment]
And is there really another issue for a class for the selected day? I can't find it at the moment

**Comment by glennwilton** [comment]
Multiple calendars work ok but they have to be the same week/day since the heights are set via CSS

Probably need to change to setting heights via styles or custom variables per calendar so no conflicts

![image](https://github.com/schedule-x/schedule-x/assets/6619768/2825d6e9-b1c7-4559-a493-d5d8540643a7)

**Comment by tomosterlund** [comment]
Added a callback `onSelectedDateUpdate` and a `getDate` method for the calendar-controls plugin

Thanks for opening this issue :)

**Comment by glennwilton** [comment]
Awesome, thanks for being so responsive.
