### ISSUE TITLE
Incompatible with remix.js due to module resolution

### ISSUE THREAD

**Issue by justin-hackin** [schedule-x/schedule-x#398]
Reproduction: https://stackblitz.com/edit/remix-run-remix-wm8xuf?file=app%2Froutes%2F_index.tsx

**Comment by justin-hackin** [comment]
If you try with `useNextCalendarApp`, nothing shows up.

**Comment by justin-hackin** [comment]
Notice, if you try to remove module type from package.json, vite reports ```The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.```

**Comment by tomosterlund** [comment]
I just tried it out in a local Remix app now, and got the calendar to render through making sure the calendar component only renders in the browser, and through removing "type": "module" in package.json of @schedule-x/react

https://github.com/tomosterlund/remix-test

Need to look into this a bit further, but it seems that in Remix you basically need to do what ClientOnly does in Nextjs, i.e. excluding the calendar from the server bundle

**Comment by tomosterlund** [comment]
OK, I got it now I think. The setup with remix and vite for some reason requires the commonjs file to be named `index.cjs` instead of `index.cjs.js`. Then everything works out of the box.

Seems like vite might not support commonjs files without the `cjs` extension (though I've seen the `{filename}.cjs.js` naming pattern in numerous libraries out there). I posted in the Vite Discord: https://discord.com/channels/804011606160703521/1235103401742962698/1235103401742962698

**Comment by tomosterlund** [comment]
Tried it out in the repo linked above now too with the version I just released, and works fine now :)

Let me know if this does the trick for you too

**Comment by justin-hackin** [comment]
Yeah, maybe I should have said something about the `*.cjs.js`, it seemed odd but my knowledge in this area is a bit weak.

Wow, great work on getting a fix in so quickly 🎉

**Comment by justin-hackin** [comment]
> I just tried it out in a local Remix app now, and got the calendar to render through making sure the calendar component only renders in the browser, and through removing "type": "module" in package.json of @schedule-x/react
> 
> https://github.com/tomosterlund/remix-test
> 
> Need to look into this a bit further, but it seems that in Remix you basically need to do what `ClientOnly` does in Nextjs, i.e. excluding the calendar from the server bundle

There's a `<NoSsr>` tag in MUI I use for this. I was curious about a remix-only solution. The file convention `component.clent.tsx` will prevent that code from being included in the server bundle, see [this](https://github.com/remix-run/remix/discussions/1023#discussioncomment-1798940).
