### ISSUE TITLE
event for click on day inside viewMonthAgenda

### ISSUE THREAD

**Issue by dovepa** [schedule-x/schedule-x#404]
Hello,

This issue follows my message on Discord regarding the implementation of an event for clicking on a day inside viewMonthAgenda.

I will try to make this modification in my spare time, but I haven't seen the documentation for updating the project. If you have it, I'm interested :)

Thank you.

**Comment by tomosterlund** [comment]
Hi. Cool that you want to have a shot at developing it :) 

Here's a guide to contributing: https://github.com/schedule-x/schedule-x/blob/main/.github/contributing.md

What do you think of naming the callback `onClickAgendaDay`?

**Comment by tomosterlund** [comment]
Actually this was added in @schedule-x/calendar 1.45.0, as `onClickAgendaDate`. I somehow seemed to miss that there was an issue for this :)
