### ISSUE TITLE
[BUG] - Schedule CSS overriding some components classes

### ISSUE THREAD

**Issue by pedrohcarvalhom** [schedule-x/schedule-x#422]
Hey, first of all, thanks for the lib, it's really great!

**Context:**

- Browser: Microsoft Edge
- Schedule-X version 1.41.0
- Vue js 3.4
- Tailwind 4

**Describe the bug**

When using PrimeVue, apparently the css styles from schedule-x is overriding some configs for some components. For example, the button.

When I comment the theme-default import, like this

```
<style>
/* @import "@schedule-x/theme-default/dist/index.css"; */
</style>
```
it shows up the buttons
![image](https://github.com/schedule-x/schedule-x/assets/109979933/d8043e0b-14ff-4753-b932-c7214ff57566)

but when I uncomment, they're gone

![image](https://github.com/schedule-x/schedule-x/assets/109979933/5dc14987-60f3-4f3a-9b2d-e92537cec4e0)

this is the browser css when they're not showing up

![image](https://github.com/schedule-x/schedule-x/assets/109979933/329bf6fc-8433-4ff9-96c9-81a38c9945f4)

[UPDATE]

I've tried use [flowbite button](https://flowbite.com/docs/components/buttons/), but still getting the same error. It looks like he does not apply some tailwind classes

```
  <button
    type="button"
    class="text-black bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm 
     px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
  >
    Default
  </button>
```

**To Reproduce**

1. Install Primevue
2. Install the schedule-x
3. Import the default theme
4. Create a custom primevue component with a button

**Comment by tomosterlund** [comment]
Hey there. Glad you like it!

Have you tried importing the CSS the way described in the docs? I don't know why it would work differently than importing it in the Vue style tag the way you do, but at least it might be worth a shot.

If that doesn't help, could you please set up a reproduction environment? I can't help much without it

**Comment by tomosterlund** [comment]
closing.

feel free to open again if you have any issues

**Comment by afrancesm** [comment]
Hello everyone! The same thing happens to me. Primevue uses @layer primevue for all its styles, so the calendar styles take precedence.
This is from primevue
![Captura de pantalla 2024-06-10 a las 15 28 44](https://github.com/schedule-x/schedule-x/assets/2932506/a0a7f75d-aab2-416e-98d3-7efe2e16cc12)
And this from schedule styles
![Captura de pantalla 2024-06-10 a las 15 28 51](https://github.com/schedule-x/schedule-x/assets/2932506/daa92bfb-e509-492c-ac59-f1332448a5a6)
Is it possible to encapsulate the calendar styles in a layer like Primevue does?

**Comment by tomosterlund** [comment]
That’s a bug, if a plain `button` rule is compiled from the styles in the schedule-x theme. I’ll need to look into that
