### ISSUE TITLE
feature: support for Bahasa language 'id-ID'

### ISSUE THREAD

**Issue by kbsangaspar** [schedule-x/schedule-x#432]
**Is your feature request related to a problem? Please describe.**  
The Bahasa (Indonesia) translation for schedule-x is currently not available.

**Describe the solution you'd like**  
I would like to see the Bahasa (Indonesia)  translation added to the calendar and date-picker.

**Things that could speed up the process**
- [X] I can picture implementing at least parts of this feature
- [X] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
💪 

Merged with: https://github.com/schedule-x/schedule-x/pull/433
