### ISSUE TITLE
Passing ISO string results in display event only in Month view

### ISSUE THREAD

**Issue by m-bartenev** [schedule-x/schedule-x#436]
If the date is in ISO string, it will be displaed _only_ on "Month" level of views.
To replicate use:

`{
          end: '2024-05-15T00:00:00Z',  
          id: '65dc14736',
          start: '2024-05-10T00:00:00Z',
          title: 'George Constanzas wedding'
 }`

**Comment by tomosterlund** [comment]
Here's what ChatGPT gave me when prompting it to write a function like that:

```
function iso8061toAgnostic(isoString) {
    // Create a Date object from the ISO 8601 string
    const date = new Date(isoString);

    // Extract individual components
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');

    // Format the date and time
    const formattedDate = `${year}-${month}-${day} ${hours}:${minutes}`;

    return formattedDate;
}

// Example usage
const isoString = "2023-05-23T14:30:00Z";
const formattedDate = iso8061toAgnostic(isoString);
console.log(formattedDate); // Output: "2023-05-23 14:30"
```

**Comment by m-bartenev** [comment]
I've got around it by formatting date to be 'YYYY-MM-DD hh:mm' or YYYY-MM-DD for the full day, but I would say it should either support the iso or don't. In my opinion it's a bit incosistent and confusing during implementation. E.g. first view I tested was the month view and switching to the week view and loosing events made me think that there is something wrong with the data flow in the app and not the format of the data I'm passing. 

Anyway, thanks for the quick response.

**Comment by tomosterlund** [comment]
But Schedule-X doesn't support ISO-8061. If there is anything in the docs that suggest otherwise, please let me know, so I can clarify :)

There is a note on time stamps here: https://schedule-x.dev/docs/calendar/events#event-time

**Comment by tomosterlund** [comment]
Closing this, since the problem seems to be resolved

open to issues for passing ISO-8061 if they include a suggestion for how the API would look and how one might achieve this on a plugin level (that is, without building it into the core library)
