### ISSUE TITLE
EventServicePlugin methods accept only string for event id

### ISSUE THREAD

**Issue by m-bartenev** [schedule-x/schedule-x#438]
Despite EventId type supporting both string and number, this plugin implements only strings usage, which requires .toString() usage while processing id. Nothing important obviously but would be nice to get it straight.
In code: https://github.com/schedule-x/schedule-x/blob/main/packages/events-service/src/events-service-plugin.impl.ts#L25

Code example in Vue/ts:

 `watch(events, () => {`
  `  eventsServicePlugin.getAll().forEach((ev) => {`
   `   eventsServicePlugin.remove(ev.id.toString())`
  `  })`
  `  events.value.forEach((ev) => calendar.events.add(ev))`
`})`

**Comment by tomosterlund** [comment]
Could it be that this is only a bug in the interface? Try passing a number to it, while using ts-ignore for that line. I think it should work.

I’ll fix this asap though
