### ISSUE TITLE
Is there a method to dynamically add calendar attributes

### ISSUE THREAD

**Issue by growthworld** [schedule-x/schedule-x#441]
The returned data is random, and each person's data is different, so it is necessary to dynamically add data
This is mainly done to distinguish different colors based on different courses

**Comment by tomosterlund** [comment]
Hi there. Thanks for taking interest in Schedule-X.

Please use the [template](https://github.com/schedule-x/schedule-x/blob/main/.github/ISSUE_TEMPLATE/feature_request.md) for creating an issue, this might help formulating an issue that I can understand and work with
