### ISSUE TITLE
Add new translate locates th-TH  (Thailand language)

### ISSUE THREAD

**Issue by bombkiml** [schedule-x/schedule-x#444]
**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  
A clear and concise description of what you want to happen. Preferably with a code example or even the API you would 
like to see.

**Additional context**  

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
Hey!

Feel free to add these translations 😊 if you need inspiration for how to achieve this, here's the last pull request for adding a language: https://github.com/schedule-x/schedule-x/pull/433 

I don't add any translations of languages I don't speak myself, but merely check them once added by others.

**Comment by tomosterlund** [comment]
Closing this, since I'm not translating.

I'm open for a PR at any time though
