### ISSUE TITLE
Month grid and agenda views A11Y improvements

### ISSUE THREAD

**Issue by statushub-bartek** [schedule-x/schedule-x#461]
Improve month grid and agenda views accessibility by:
1. Adding `aria-label` attribute containing full date to day cells like it is done for day columns in week and day views
2. Adding `aria-label` attribute containing full date to month grid's "+n events" button

**Comment by tomosterlund** [comment]
1st one makes perfect sense to me.

2nd one, maybe: "Link to {date}"?

**Comment by statushub-bartek** [comment]
It would be nice to inform the screen reader also about amount of hidden events, what do you think about something like "Link to {n} more events on {date}"?

**Comment by tomosterlund** [comment]
I think that makes sense too!
