### ISSUE TITLE
No callback for month agenda view day click

### ISSUE THREAD

**Issue by statushub-bartek** [schedule-x/schedule-x#462]
**Context:**
- Latest versions of Chrome, Firefox and Safari
- schedule-x v1.42.3

**Describe the bug**
There is no callback being triggered on month agenda view day click.

**Expected behavior**
Month grid's `onClickDate` or a separate callback for month agenda being triggered on day click.

**Comment by tomosterlund** [comment]
Thanks!

I think the safest option here to avoid unwanted breaking changes, is to add another event like `onAgendaDayClick`

**Comment by tomosterlund** [comment]
Added it as `onClickAgendaDate`
