### ISSUE TITLE
Calendar action buttons stop working after...

### ISSUE THREAD

**Issue by mikeabbott10** [schedule-x/schedule-x#473]
Vue 3.4.19.
View: viewMonthGrid or viewMonthAgenda

Changing month (or using others action buttons) after opening an event modal (i use event-modal plugin) results in a bug: the buttons don't work anymore.

![schedulex](https://github.com/schedule-x/vue/assets/10254588/fb194ed2-12e6-4a83-afad-b9eadfb587ee)

```
<template>
   <ScheduleXCalendar
      :calendar-app="calendarApp"
    >
      <template v-slot:eventModal="{ calendarEvent }">
        <div class="event-modal">
          ...
        </div>
      </template>
    </ScheduleXCalendar>
</template>

<script>
  ...
  const calendarApp = createCalendar({
    views: [viewMonthGrid, viewMonthAgenda],
    defaultView: viewMonthGrid.name,
    plugins: [
      createEventModalPlugin()
    ],
    events: events
  })
</script>
```

**Comment by mikeabbott10** [comment]
Console is empty unfortunately

**Comment by tomosterlund** [comment]
Btw are you on the latest version of `@schedule-x/vue`? There was a fix last week for a similar problem

**Comment by tomosterlund** [comment]
I’ll go ahead and assume that this was fixed by this commit: https://github.com/schedule-x/schedule-x/commit/2fb2f71f993bce04915cad2a0a355a4bde3847d9

if your problem persists even when upgrading though, please open an issue again
