### ISSUE TITLE
Vue week view

### ISSUE THREAD

**Issue by Revadike** [schedule-x/schedule-x#478]
I am forced to use `1.38.0` for `@schedule-x/vue`, because the latest version does not show the week view by default. The only workaround is to trigger a window resize event.

**Comment by tomosterlund** [comment]
Do you set `defaultView` to `viewWeek.name`?

Please always include more context data when you open issues. I'd very much like to help you, but without code for setup, version numbers, or best case even a minimal reproduction environment, it's hard to be of any help.

When I try setting the week view on page load it works.

**Comment by Revadike** [comment]
> Do you set `defaultView` to `viewWeek.name`?
Yes

> Please always include more context data when you open issues. 
This is what I am currently using:
```
npm ls
├── @mdi/font@7.4.47
├── @nuxt/devtools@1.3.2
├── @nuxt/eslint-config@0.2.0
├── @nuxt/types@2.17.3
├── @nuxtjs/google-fonts@3.2.0
├── @pinia-plugin-persistedstate/nuxt@1.2.0
├── @pinia/nuxt@0.5.1
├── @preact/signals@1.2.3
├── @schedule-x/calendar-controls@1.45.1
├── @schedule-x/calendar@1.45.1
├── @schedule-x/drag-and-drop@1.45.1
├── @schedule-x/event-modal@1.45.1
├── @schedule-x/event-recurrence@1.45.1
├── @schedule-x/resize@1.45.1
├── @schedule-x/theme-default@1.45.1
├── @schedule-x/vue@1.38.0
├── algoliasearch@4.23.3
├── cropperjs@1.6.2
├── dotenv@16.4.5
├── eslint-plugin-vue@9.26.0
├── eslint-plugin-vuetify@2.4.0
├── eslint@8.57.0
├── export-to-csv@1.3.0
├── firebase-tools@13.10.2
├── firebase@10.12.2
├── linkify-string@4.1.3
├── linkifyjs@4.1.3
├── lodash@4.17.21
├── napi-wasm@1.1.0 extraneous
├── nuxt@3.11.2
├── pinia@2.1.7
├── preact@10.22.0
├── qrcode@1.5.3
├── rrule@2.8.1
├── sass@1.77.2
├── vite-plugin-vuetify@2.0.3
├── vue-eslint-parser@9.4.2
├── vue-pdf-embed@2.0.3
├── vue-recaptcha-v3@2.0.1
├── vue-router@4.3.2
├── vue@3.4.27
└── vuetify@3.6.7
```
```
node --version
v18.17.1
```

So, I had this issue in the past, even this morning, but somehow now, I cannot reproduce it anymore. I will close it for now.
