### ISSUE TITLE
setDate in viewMonthAgenda broken / unexpected behavior (vue)

### ISSUE THREAD

**Issue by samydoesit** [schedule-x/schedule-x#487]
Hi i was trying to set a date on the Month Agenda view but it behaves unexpectedly.

**Context:**

- Browser [chrome latest]
- Schedule-X [v1.46.1]
- Schedule-X/vue [v1.43.3]

**To Reproduce**

1. Go to https://stackblitz.com/edit/github-iaect9?file=package.json,components%2Fapp-calendar.vue
2. Click on 'Set Date'
3. View does not update correctly (only the value in the input changes)

**Expected behavior**

View updates correctly to specified date

**Screenshots**
<img width="547" alt="image" src="https://github.com/schedule-x/schedule-x/assets/15785987/65231d21-d12c-4ed6-b1d2-9bec8042da7a">

**Comment by tomosterlund** [comment]
Thanks a lot for reporting!

looks to me, like there’s just a missing `useEffect` hook listening on the selected date.
