### ISSUE TITLE
Init callback that returns ranges

### ISSUE THREAD

**Issue by vukadinFE** [schedule-x/schedule-x#494]
**Is your feature request related to a problem? Please describe.**  
There is no way to get ranges when the calendar is loaded. Only when you change the view or date is the `onRangeUpdate` callback fired.

**Describe the solution you'd like**  
It would be neat if `onRangeUpdate` fires on calendar init or if we have another init callback that can return ranges and whatever else is needed.

**Comment by tomosterlund** [comment]
In `@schedule-x/calendar@1.48.0` you can now do this:

```ts
const calendarControlsPlugin = createCalendarControlsPlugin()
const calendar = createCalendar({
  // your config
  plugins: [calendarControlsPlugin]
})

calendarControlsPlugin.getRange()

calendar.render(yourElement)

```
