### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'timeGridEvents')

### ISSUE THREAD

**Issue by amitpjoshiem** [schedule-x/schedule-x#503]
Thank you for wanting to take the time to report a problem. In order to increase the chances of the issue being 
resolved,
please take a moment to give as much relevant information as possible.

**Context:**

- Browser chrome 
- Browser-version
- Schedule-X version : 1.46.7

**Describe the bug**

On month view, for the **current date** if we are having more events, it shows '+ N Events' if user is clicking on it, it will show error on console like 
```
@schedule-x_calendar.js?v=0e3c3f4b:4245 Uncaught TypeError: Cannot read properties of undefined (reading 'timeGridEvents')
    at positionInTimeGrid (@schedule-x_calendar.js?v=0e3c3f4b:4245:18)
    at sortEventsIntoDateAndTimeGrids (@schedule-x_calendar.js?v=0e3c3f4b:4404:15)
    at WeekWrapper._a [as __] (@schedule-x_calendar.js?v=0e3c3f4b:4413:5)
    at B2 (@schedule-x_calendar.js?v=0e3c3f4b:416:15)
    at Array.forEach (<anonymous>)
    at j2 (@schedule-x_calendar.js?v=0e3c3f4b:359:40)
```

and it will redirect to "Day view", without showing events for the day.

**To Reproduce**

1. Go to https://stackblitz.com/edit/vitejs-vite-ykzyq3?file=src%2FApp.vue,package.json
2. on App.vue, change events start & end dates with current date
3. run the program on new tab to see month view.
4. click on "+ N events" for current date
5. on console, you will see that error

**Expected behavior**

On clicking on "+N events" it should not shown any errors and it should show all events of current date in "Day" & week view

**Screenshots**

https://github.com/schedule-x/schedule-x/assets/123377333/8ce5aeae-93e3-4371-8b4f-03cfe19ea16e

**Comment by tomosterlund** [comment]
Thanks for such a detailed issue. Like I said, I still couldn't reproduce, but I'm pretty sure I've found the code that seems to be causing a problematic race condition.

Will try and make a release tomorrow or later this week with the fix

**Comment by amitpjoshiem** [comment]
Thanks @tomosterlund , its working...

**Comment by tomosterlund** [comment]
Glad to hear :)
