### ISSUE TITLE
Scroll plugin not working on Vue 3 - Nuxt 3

### ISSUE THREAD

**Issue by fleonardelli** [schedule-x/schedule-x#513]
Thank you for wanting to take the time to report a problem. In order to increase the chances of the issue being 
resolved,
please take a moment to give as much relevant information as possible.

**Context:**

- Browser: chrome
- Browser-version:  126.0.6478.61
- Schedule-X version:
    "@schedule-x/current-time": "^1.47.1",
    "@schedule-x/event-modal": "^1.47.0",
    "@schedule-x/scroll-controller": "^1.47.1",
    "@schedule-x/theme-default": "^1.47.0",
    "@schedule-x/vue": "^1.44.0",

**Describe the bug**

Adding the scroll controller plugin to the componen is not scrolling to the initial time.
scrollTo method isn't working either.

**To Reproduce**

1. Create a new calendar 
```
const createCalendarInstance = () => {
  const scrollController = createScrollControllerPlugin({ initialScroll: '08:00' });
  calendarApp.value = createCalendar({
    selectedDate: new Date().toISOString().split('T')[0],
    views: [viewDay, viewWeek, viewMonthGrid, viewMonthAgenda],
    defaultView: viewWeek.name,
    events: events.value,
    plugins: [
      createCurrentTimePlugin({ fullWeekWidth: true }),
      createEventModalPlugin(),
      scrollController
    ],
    locale: 'es-ES',
  });
 // scrollController.scrollTo('14:00')
};
````

2. Reload the page and see that the calendar did not scroll to 8, nor 14. 
3. If `scrollController.scrollTo('14:00')` uncommented, then an error in shown in the console:
```
Uncaught (in promise) Error: [Schedule-X error]: Plugin not yet initialized. You cannot scroll before the calendar is rendered. For configuring the initial scroll, use the `initialScroll` parameter
    at ScrollControllerPlugin.scrollTo (@schedule-x_scroll-controller.js?v=234b3112:107:13)
```

Seems like the plugin is not initialized correctly?

**Expected behavior**

Calendar to scroll to the configured time.

**Screenshots**

**Comment by tomosterlund** [comment]
Thanks for opening this issue. However, I cannot reproduce the problem with `initialScroll`. Could you set up a reproduction environment on Stackblitz?

Regarding `scrollTo`: the plugin is not **yet initialized**. You just can't use it before the calendar has been painted in the browser.

**Comment by tomosterlund** [comment]
I just added the scroll plugin to the Nuxt-example: https://github.com/schedule-x/nuxt-example

You could check that out, and compare to your implementation

**Comment by vivibru** [comment]
I have the same issue with Vue 3 and TypeScript:

```
"@schedule-x/calendar-controls": "^1.45.0",
"@schedule-x/event-modal": "^1.45.0",
"@schedule-x/event-recurrence": "^1.45.0",
"@schedule-x/events-service": "^1.45.0",
"@schedule-x/scroll-controller": "^1.47.1",
"@schedule-x/theme-default": "^1.45.0",
"@schedule-x/vue": "^1.42.0",
"vue": "^3.4.21",
"typescript": "~5.4.0"
```

I tried using the example in my project, but it doesn't work for me.

**Comment by tomosterlund** [comment]
> I have the same issue with Vue 3 and TypeScript:
> 
> ```
> "@schedule-x/calendar-controls": "^1.45.0",
> "@schedule-x/event-modal": "^1.45.0",
> "@schedule-x/event-recurrence": "^1.45.0",
> "@schedule-x/events-service": "^1.45.0",
> "@schedule-x/scroll-controller": "^1.47.1",
> "@schedule-x/theme-default": "^1.45.0",
> "@schedule-x/vue": "^1.42.0",
> "vue": "^3.4.21",
> "typescript": "~5.4.0"
> ```
> 
> I tried using the example in my project, but it doesn't work for me.

Have you tried updating all dependencies to their latest versions also?

If you do, and it still doesn't work, could it be that you have some global styles in your project that override the overflow styles of Schedule-X?

Maybe check that nothing is overriding this `overflow-y`?
<img width="1699" alt="Bildschirmfoto 2024-07-03 um 06 19 04" src="https://github.com/schedule-x/schedule-x/assets/63011648/2d362ff9-59ff-49ae-97f0-ea9c6615e545">

**Comment by fleonardelli** [comment]
@tomosterlund @vivibru 

Adding the style:

```

<style>
.sx-vue-calendar-wrapper {
  height: 700px;
  max-height: 90vh;
  width: 100%;
}
</style>
```

Makes it work. Seems like by default it uses the full height, so there is no overflow. 

thanks! 

@vivibru please lmk if it works, so I can close the issue
