### ISSUE TITLE
Clicking on more (+n events) triggers onClickDay

### ISSUE THREAD

**Issue by vukadinFE** [schedule-x/schedule-x#516]
**Describe the bug**
Clicking on a "+n events" (`.sx__month-grid-day__events-more`) button in the mouth-grid view triggers an `onClickDay` callback.

**Expected behavior**
The `onClickDay` callback should not be called when clicking a  "+n events" button.
_Reason: callback could be used to open a custom modal or something else, so it's unexpected to do it when clicking on the "+n evens" button_

**Additionally**
It would be perfect if we had a `.sx__month-grid-day__header-date` click callback, or extra boolean property that will determine if clicking on a day number in the mount-grid view should switch to day view (just as "+n events" do).

**Comment by tomosterlund** [comment]
I'll release a fix for this in a moment.

Regarding the **additionally**-section. I think this makes sense, but could you transfer that request to a new issue? I looked into this a little, and it would require a breaking change for me to do so, so it'll have to be part of v2.

**Comment by vukadinFE** [comment]
Many thanks. I appreciate.
