### ISSUE TITLE
Dropdown closes eventModal

### ISSUE THREAD

**Issue by goca987** [schedule-x/schedule-x#521]
If we have a dropdown in the eventModal it closes as we select a value from the dropdown.

**Comment by tomosterlund** [comment]
For some more context (from Discord chat):

> **goca987:**
> Hey @TomÖsterlund I am using the eventModal, and i have a dropdown in it. As soon as I select a value from the dropdown the eventModal gets closed. As I am using vuetify, I tried to use v-dialog inside the eventModal, and in that case the issue disappeared,  but the v-dialog is acting really weird. 

> **Tom Österlund**
> Hey! That makes sense, since most dropdown libraries use portals to render the elements to the body.
> 
> Would maybe make sense to either:
> 1) enable adding a custom callback for the click outside listener
> 2) allow disabling the click outside listener, and let the implementer just write their own logic for this, wherever they want.
> 
> What do you think?

I'm open to PRs for option 1, but probably I won't put in the time to achieve this myself anytime soon
