### ISSUE TITLE
(Vue) enable saving calendar instance in reactive proxies

### ISSUE THREAD

**Issue by rswalrond** [schedule-x/schedule-x#534]
Context:

Browser: testing on edge 
Browser version:  125.0.2535.92
Schedule-X version: 1.5.0
Describe the bug

After switching from Month view back to any other view (Week or Day), the date picker and navigation arrows ('<' and '>') at the top of the screen no longer respond or switch the date correctly. Manually selecting a date in the picker and re-clicking the current view temporarily restores some functionality but does not fully resolve the issue. Additionally, the calendar view itself remains broken, impacting overall usability.

To Reproduce

Navigate to the calendar.
Start in Week view.
Use the date picker and navigation arrows ('<' and '>') to switch between weeks or days.
Switch to Day view and verify functionality.
Switch to Month view.
Attempt to switch back to Week or Day view using the date picker or navigation arrows.
Observe that events do not fire, and the date does not switch correctly.
Manually select a date in the date picker.
Re-click on the current view (e.g., Day view) to partially restore functionality.
Expected behavior

Upon switching back from Month view to Week or Day view, the date picker and navigation arrows should continue to function as expected, allowing users to switch dates seamlessly without needing manual intervention. The calendar view should remain fully functional without any issues.

Screenshots
![day-working](https://github.com/schedule-x/schedule-x/assets/139915998/af3688ea-d25d-4acd-adb2-c9940c338845)
![month-working](https://github.com/schedule-x/schedule-x/assets/139915998/3c3ca613-749e-4041-8a37-6522d21f8608)
![week-working](https://github.com/schedule-x/schedule-x/assets/139915998/5a0a25ed-bd76-4eb1-b311-96f6358843c1)
![day-not-working](https://github.com/schedule-x/schedule-x/assets/139915998/de17f55f-d170-433b-8673-a572dd3cd6b3)
![week-not-working](https://github.com/schedule-x/schedule-x/assets/139915998/6eb5fc80-33db-43c4-846e-c5d04193e2ef)

**Comment by tomosterlund** [comment]
are you really on `@schedule-x/calendar@1.5.0` ? In that case, please update, since we are 45 minor versions beyond that.

Otherwise, could you please post the set up code? Because I can't reproduce this, so it might be related to your implementation

**Comment by tomosterlund** [comment]
One of the most common errors lately, is people trying to add javascript dates into the calendar, leading to strange behavior that I've never seen before. Could that be the case for you?

**Comment by rswalrond** [comment]
Here is what I found out. Using the Vue Lifecycle approach does not work. Take this sample code where I'm simulating loading the calendars and events from an api call. If you switch to month view and then switch away, changing the date the calendar no longer responds.
`<script setup>
import { onMounted, ref } from 'vue';
import { ScheduleXCalendar } from '@schedule-x/vue';
import { createCalendar, viewDay, viewWeek, viewMonthGrid, viewMonthAgenda } from '@schedule-x/calendar';
import '@schedule-x/theme-default/dist/index.css';

// Refs for calendar app and events
const calendarApp = ref(null);
const calendars = ref([]);
const events = ref([]);

// Function to simulate fetching calendar data from an API
function fetchCalendars() {
  return [
    { id: '1', name: 'Personal', color: 'blue' },
    { id: '2', name: 'Work', color: 'red' },
    // Add more calendars with their respective colors
  ];
}

// Function to simulate fetching events data from an API
function fetchEvents() {
  return [
    { calendarId: '1', id: 1, title: 'Doctor Appointment', start: '2023-12-19', end: '2023-12-19' },
    { calendarId: '1', id: 2, title: 'Lunch with Sarah', start: '2023-12-20 12:00', end: '2023-12-20 13:00' },
    { calendarId: '2', id: 3, title: 'Team Meeting', start: '2023-12-21', end: '2023-12-21' },
    { calendarId: '2', id: 4, title: 'Project Deadline', start: '2023-12-22 14:00', end: '2023-12-22 15:00' },
    // Add more events associated with calendar IDs
  ];
}

onMounted(() => {
  calendars.value = fetchCalendars();
  events.value = fetchEvents();
  calendarApp.value = createCalendar({
    selectedDate: '2023-12-19',
    views: [viewDay, viewWeek, viewMonthGrid, viewMonthAgenda],
    defaultView: viewWeek.name,
    calendars: calendars.value,
    events: events.value,
  });
});
</script>

<template>
  <div v-if="calendarApp">
    <ScheduleXCalendar :calendar-app="calendarApp" />
  </div>
</template>`

**Comment by rswalrond** [comment]
however doing this, seems to work.
`import { ScheduleXCalendar } from '@schedule-x/vue'
import { createCalendar, viewDay, viewWeek, viewMonthGrid, viewMonthAgenda } from '@schedule-x/calendar'
import '@schedule-x/theme-default/dist/index.css'

// Function to simulate fetching calendar data from an API
function fetchCalendars() {
  return [
    { id: '1', name: 'Personal', color: 'blue' },
    { id: '2', name: 'Work', color: 'red' },
    // Add more calendars with their respective colors
  ];
}

// Function to simulate fetching events data from an API
function fetchEvents() {
  return [
    { calendarId: '1', id: 1, title: 'Doctor Appointment', start: '2023-12-19', end: '2023-12-19' },
    { calendarId: '1', id: 2, title: 'Lunch with Sarah', start: '2023-12-20 12:00', end: '2023-12-20 13:00' },
    { calendarId: '2', id: 3, title: 'Team Meeting', start: '2023-12-21', end: '2023-12-21' },
    { calendarId: '2', id: 4, title: 'Project Deadline', start: '2023-12-22 14:00', end: '2023-12-22 15:00' },
    // Add more events associated with calendar IDs
  ];
}

const calendarApp = createCalendar({
  selectedDate: '2023-12-19',
  views: [viewDay, viewWeek, viewMonthGrid, viewMonthAgenda],
  defaultView: viewWeek.name,
  calendars: fetchCalendars(), // Set the calendars in the configuration
  events: fetchEvents(),
});
</script>

<template>
  <div>
    <ScheduleXCalendar :calendar-app="calendarApp" />
  </div>
</template>`

**Comment by tomosterlund** [comment]
That’s a known problem that I believe I have briefly commented in the docs: saving the calendar app or its views in reactive proxies break the calendar

we can keep this issue open as a reminder for me to look into this, but you can probably fix your problem by just saving your calendar instance in a normal variable

**Comment by tomosterlund** [comment]
No worries! Thanks for reporting
