### ISSUE TITLE
is-selected class for week- and month grids

### ISSUE THREAD

**Issue by vukadinFE** [schedule-x/schedule-x#538]
Can we have a highlight modifier class on `.sx__month-grid-day`(month view) and `.sx__time-grid-day`(week view) elements?

**Comment by tomosterlund** [comment]
I don't understand completely. Could you share an image of what you mean, or try to elaborate the thought?

**Comment by vukadinFE** [comment]
Sorry that I wasn't clear enough.
I want to highlight the selected date in the month and week view.
I am doing it custom currently by adding a CSS class to the selected day, but it's a hackish solution. I am adding setTimeouts because the markup is not ready as soon as the selected date updates.
