### ISSUE TITLE
(React) Create usePlugin hook

### ISSUE THREAD

**Issue by RimikShivansh** [schedule-x/schedule-x#545]
**My ReactJs Code**

```
import {
  viewDay,
  viewMonthAgenda,
  viewMonthGrid,
  viewWeek,
} from "@schedule-x/calendar";
import { assetsFundingCashFlowCalendarData } from "../../../../../store/slices/cashFlowSlice/cashFlowSlice";
import { createEventsServicePlugin } from "@schedule-x/events-service";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

const AssetsFlowPage = () => {
  const assetsFundingCashFlowCalendarInfo = useSelector(assetsFundingCashFlowCalendarData);
  const eventsServicePlugin = createEventsServicePlugin();

  const dispatch = useDispatch();
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  const currentMonth = currentDate.getMonth() + 1;

  const calendar = useCalendarApp({
    defaultView: viewMonthGrid.name,
    views: [viewDay, viewWeek, viewMonthGrid, viewMonthAgenda],
    events: assetsFundingCashFlowCalendarInfo,
    plugins: [eventsServicePlugin],
    callbacks: {
      onSelectedDateUpdate(date) {
        const year = date.split("-")[0];
        const month = date.split("-")[1];
        dispatch(
          getAssetsFundingCashFlowCalendarDataAsync({
            year,
            month,
            accessToken,
          })
        );
      },
    },
  });
  
   useEffect(() => {
    dispatch(
      getAssetsFundingCashFlowCalendarDataAsync({
        year: currentYear,
        month: currentMonth,
        accessToken,
      })
    )
  }, []);
  
 useEffect(() => {
    if (assetsFundingCashFlowCalendarInfo > 0) {
      eventsServicePlugin.set(assetsFundingCashFlowCalendarInfo);
      console.log("Set: ", assetsFundingCashFlowCalendarInfo);
    }
  }, [assetsFundingCashFlowCalendarInfo]);
  
   return ( <div>
   <ScheduleXCalendar calendarApp={calendar} />
   </div>)
```
 
 **The eventsServicePlugin is not working in this case**
 
 API RESPONSE:
```
 [
    {
      id: 1,
      title: 'Coffee with John',
      start: '2024-07-12',
      end: '2024-07-12',
    }
  ]
```
 
 Expected behaviour is whenever the value inside useSelector changes the data on the calendar should be updated
 The Data is properly getting logged but not updated inside useEffect

**VERSIONS USED**

- "react": "^18.2.0"
- "react-dom": "^18.2.0"
- "@schedule-x/events-service": "^1.50.0"
- "@schedule-x/react": "^1.38.0
- "@schedule-x/theme-default": "^1.41.0"
- node version: v20.12.2
- npm version: 10.5.0
- "@reduxjs/toolkit": "^2.2.3"

**Comment by tomosterlund** [comment]
Do you have any errors in your console? My assumption would be that you are getting an error that you cannot call `set` on `undfined`. In this case, you need to make adjustments to your code so that the events service doesn't get thrown away when your component re-renders. You could either save your service over re-renders in `useState`, or instantiate it outside of your component, like this:

```tsx

const eventsServicePlugin = createEventsServicePlugin();

const AssetsFlowPage = () => {
  // ... other stuff
```

**Comment by tomosterlund** [comment]
Actually we can keep this open. It probably would make sense for the library to have some kind of `usePlugin` hook that lets you save a plugin across re-renders, and basically just saves a plugin in `useState` behind the scenes

**Comment by tomosterlund** [comment]
and if you move this statement to just above your component `const eventsServicePlugin = createEventsServicePlugin();`?

**Comment by RimikShivansh** [comment]
Tried this, its still not working

**Comment by tomosterlund** [comment]
Then I will need a reproduction environment to be able to help. Setting one up in Stackblitz is usually quite fast

**Comment by RimikShivansh** [comment]
Stackblitz Reactjs Code URL: `https://stackblitz.com/edit/react-udlh2d?file=src%2FApp.js`
This is not the actual code, just a dummy code written to understand the problem properly

Here useSelector value changes and it is being assigned to calendar but calendar view is not being updated accordingly

Backend API used is also dummy: `https://calendar-backend-z9ki.onrender.com/`
it only accepts `/calendar/1` or `/calendar/2` endpoints.

On initial component load `/calendar/1` API is called and after that if the month is changed `/calendar/2` API gets called and updates the state

**Comment by tomosterlund** [comment]
This is a problem with your application code. See the console.log in the `useEffect` hook, doesn't run after your promises are fulfilled
<img width="1714" alt="Bildschirmfoto 2024-07-13 um 10 38 38" src="https://github.com/user-attachments/assets/cf849353-8803-4d30-b689-f1d390c78b1b">

**Comment by RimikShivansh** [comment]
I have updated the code `https://stackblitz.com/edit/react-udlh2d?file=src%2FApp.js` and now useEffect is logging updated state result after API calls but calendar view does not update with it

https://github.com/user-attachments/assets/a28bb351-ad99-4ff2-8910-5186276f8d83

**Comment by tomosterlund** [comment]
I can reproduce the issue now, but really clueless at the moment what's causing it.

If I synchronously add events in your no-dependency hook, things work, but once used via this dispatch method, it doesn't.

Will need to look into this further

**Comment by tomosterlund** [comment]
I have an interesting finding:

when I use a no-dependency hook in your example, without any use of the react-redux stuff, I can use the events service without a problem. As soon as I comment that `dispatch` statement back in, it doesn't work anymore, even though the code runs.

It appears to me as if the calendar instance is thrown away, and a new one is set up. That means the events-service plugin is then only used with the old calendar instance which is not rendered anymore, but just kept in memory through the events service plugin. If you compare the console.log outputs with and without the `dispatch` statement, you'll see in the first output, the internal `calendarEvents` is matching in both outputs. Once I use the `dispatch` statement, the `calendarEvents` list from the app of events service plugin, is another list of events than the one used by the currently rendered calendar.

Any ideas on what could cause this?

The `useCalendarApp` hook is basically just a wrapper around Reacts `useState`, like:

```tsx
export function useCalendarApp(config: CalendarConfig) {
  const [calendarApp] = useState(createCalendar(config))
  return calendarApp
}
```

https://github.com/user-attachments/assets/4fc6e115-7714-4ba6-93d7-a15f1d2f5223

**Comment by RimikShivansh** [comment]
Here is a code generated by ChatGPT to memoize calendar instance so it doesn't change on each render, it still doesn't seems to work

```
import {
  viewDay,
  viewMonthAgenda,
  viewMonthGrid,
  viewWeek,
} from '@schedule-x/calendar';
import { useCalendarApp, ScheduleXCalendar } from '@schedule-x/react';
import { createEventsServicePlugin } from '@schedule-x/events-service';
import React, { useEffect, useMemo } from 'react';
import { getCalendarData, calendarData, dataLoading } from './commonSlice';
import { useDispatch, useSelector } from 'react-redux';

import '@schedule-x/theme-default/dist/index.css';

const eventsServicePlugin = createEventsServicePlugin();

export default function App() {
  const calendarInfo = useSelector(calendarData);
  const calendarDataStatus = useSelector(dataLoading);
  const dispatch = useDispatch();

  const calendar = useMemo(() => useCalendarApp({
    defaultView: viewMonthGrid.name,
    views: [viewDay, viewWeek, viewMonthGrid, viewMonthAgenda],
    plugins: [eventsServicePlugin],
    events: [],
    callbacks: {
      onSelectedDateUpdate() {
        dispatch(getCalendarData(2));
      },
    },
  }), [dispatch]); // Memoize calendar instance

  useEffect(() => {
    dispatch(getCalendarData(1));
  }, [dispatch]);

  useEffect(() => {
    if (calendarDataStatus === 'success') {
      eventsServicePlugin.set(calendarInfo);
      console.log(calendarInfo);
    }
  }, [calendarDataStatus, calendarInfo]);

  return (
    <div>
      <ScheduleXCalendar calendarApp={calendar} />
    </div>
  );
}

```

**Comment by tomosterlund** [comment]
I downloaded your fork and played around with it a bit locally. I now understand part of the problem better:

Problem 1: the useState hook in the `useCalendarApp` hook seems to be reinitialized many times over, instead of persisting its state. I recreated the original hook like this with a console log, and saw how the console log was executed many times in your example: https://github.com/tomosterlund/sx-react-debugging-example/blob/main/src/useCalendar.js

Problem 2 (still unsolved): something is causing the useState-hook inside `useCalendar` to be reinitialized, meaning it creates a whole new calendar instead of using the last one.

**Comment by tomosterlund** [comment]
This was an error in the `useCalendarApp` hook. If you download the latest version of `@schedule-x/react`, this problem should be fixed.

Thank you so much again, for providing the repro and useful insights. I wouldn't have solved this bug anytime soon without it
