### ISSUE TITLE
(Vue) Add slot for the entire calendar header

### ISSUE THREAD

**Issue by mariela-plaza** [schedule-x/schedule-x#546]
First of all, thank you for creating this library, I've enjoyed playing around with it a lot.

I have seen in the Vue docs that the are several slots for prepending and appending things on the right and left sides of the header but there isn't a slot to replace the entire header itself. I think it would be really interesting to have one so that the user can create the header they want for the calendar.

I'm thinking that in order to move around to different days, weeks or months in a custom header the user could use the Calendar Controls plugin. I haven't played around much with it but they could use the setDate method to move around the Calendar as necessary.

Once again, thank you for this great resource!

**Comment by tomosterlund** [comment]
I think that’s a good idea 👍 if you need it urgently, I’m open to PRs for it. Otherwise I’ll just put it on my list of todos for once I’ve gotten past my problems with the React adapter

**Comment by mariela-plaza** [comment]
Thank you so much! For the time being is not urgent but I thought it would be a nice feature to have.
Have a great day and good luck with the React adapter problems :)

**Comment by Omicrxn** [comment]
+1 to this, I'd like more customization in the header or also the possibility to hide it and make my own (in this case there should be enough functions available to make it work). Great work btw!
