### ISSUE TITLE
Month grid events visibility logic bug

### ISSUE THREAD

**Issue by statushub-bartek** [schedule-x/schedule-x#559]
**Context:**
- Chrome/Firefox/Safari
- Schedule-X v1.46.7
- replicable at https://premium.schedule-x.dev/

**Describe the bug**
I found scenarios where the "+n events" button is visible and shows incorrect `n` value despite there is only one event shown for that day (which is also not true). Another scenario hides the "+n events" button while there are invisible events for that day.

**To Reproduce**
1. Create 6 events lasting for full month, let's take July 2024
2. Create a one-day event somewhere in the middle of the week, let's take 10th of July 2024
3. Month grid shows first 4 full-month events with "+3 events" for July 10th and "+2 events" for others - OK
4. Edit fist two full-month events end dates to finish on July 9th
5. Month grid for July 10th shows 3rd and 4th full-month events, the one-day event and "+1 event" button which gives 4, but there are 5 events on that day (week and day views shows 5 events) - BUG
6. Edit 3rd full-month event's end date to finish on July 9th
7. Month grid for July 10th shows 4th full-month event, the one-day event and no "+n events" button, but there are 4 events on that day - BUG
8. Edit fourth full-month event's end date to finish on July 9th
9. Month grid for July 10th shows only the one-day event, but there are 3 events on that day - BUG

NOTE: all events are not full-day and all are being created in the same calendar.

**Expected behavior**
I believe that the Google Calendar month grid should be an example of correct behavior here - for example in step 5 it would hide first 2 long-term events which finishes on July 9th under "n more events" and show the ones that are lasting through all month instead (3rd, 4th and 5th in that case).

**Screenshots**
Step 5 - month grid
<img width="931" alt="step 5 - month grid" src="https://github.com/user-attachments/assets/b24b4734-f264-46b1-92d3-54c3bc54e950">

Step 5 - week grid
<img width="931" alt="step 5 - week grid" src="https://github.com/user-attachments/assets/00b81852-5843-49e5-b85e-5d6a98804e32">

**Comment by tomosterlund** [comment]
Thanks for your example, I'll check this out later. When you say "edit", what exactly do you mean by that?

**Comment by statushub-bartek** [comment]
The reproduction steps apply to the example on https://premium.schedule-x.dev/ - I've been using the interactive event modal to walk you through few cases, but the edition itself is not important, cause in my app the calendar with initially loaded data already contains the bug.

**Comment by tomosterlund** [comment]
The numbers in your example don't add up:

1. Create 6 events lasting for full month, let's take July 2024 **(6 in total)**
2. Create a one-day event somewhere in the middle of the week, let's take 10th of July 2024 **(7 in total)**
3. Month grid shows first 4 full-month events with "+4 events" for July 10th and "+3 events" for others - OK **(still 7 in total, so 4 plus 4 can't make sense?)**

**Comment by tomosterlund** [comment]
When I follow your steps to the point, I have 3 full-month events and the single day event at step 7, like I'd expect it to be.

**Comment by tomosterlund** [comment]
No matter how many times I try to follow this, by the time I get to step 5, where the bug is supposed to show I can't reproduce it; instead I have the 3rd, 4th, 5th, and 6th full day events and a +1 for the one day event on the 10th of July, and this is to be expected.

Do you mind shooting a video of your example, zip it and send it to me, because I can't reproduce this

**Comment by statushub-bartek** [comment]
I can reproduce it each time, please take a look:
https://app.birdeatsbug.com/dZZTRhGCcHXhE-UDgd9ZkNfOci67607qlvvWGO09MAr6?detailsHidden=true

Maybe my reproduction steps were not precise enough.

**Comment by tomosterlund** [comment]
whoa OK, that's wild. Thanks for sharing

**Comment by tomosterlund** [comment]
So there are 2 problems addressed here. The one is inarguably a bug:

1. **inarguably a bug**: 11-14th July in your image above does not display that there are additional events, although there would be 2 more events to view.
2. **not necessarily a bug, but perhaps room for improvement**:

> I believe that the Google Calendar month grid should be an example of correct behavior here - for example in step 5 it would hide first 2 long-term events which finishes on July 9th under "n more events"

This is not always true in Google: see example image. In Google they seem to have the same problem: events between 1-9 September are prioritized in the second week of September, even when this means that events spanning 1-30 will be hidden in the second week of September, despite there being room for them. Now, I see that this is not optimal, and maybe there would be some solution to fix this. Off the top of my head though, I can't think of what that solution would be.

![Bildschirmfoto 2024-07-26 um 18 14 34](https://github.com/user-attachments/assets/cec18714-3714-4497-abe2-5cade00b667c)

That said, I'll get on top of the obvious bug with the missing **+ n events**. I'll also try and think of whether I find a prettier algorithm to position the events in the month, but there is a real risk I might not be able to achieve something even the Google Calendar engineers didn't 😬

**Comment by tomosterlund** [comment]
I realized a way that this can probably be improved by improving the sorting algorithm a little bit for the month. Currently, the month sorts events by `start` and `end` before taking any decision about where to position an event. If I start stripping all datetime formats of their time, meaning `YYYY-MM-DD HH:mm` turns into `YYYY-MM-DD` for the sorting only, your example above would be improved a little, because all full-month events would get a higher prio in the grid than events that start on the same day, but end on the 9th.
