### ISSUE TITLE
feat: add Ukrainian language support

### ISSUE THREAD

**Issue by Polkilof** [schedule-x/schedule-x#573]
I sent you files with the Ukrainian translation already added to your email (tom@schedule-x.dev)
It would be cool if you added it
[uk-Ua traslate.zip](https://github.com/user-attachments/files/16430893/uk-Ua.traslate.zip)

**Comment by tomosterlund** [comment]
Hi 👋 thanks for taking the time to translate it. don’t you want to add them directly via a fork and a pull request?

I can do it too, but currently I’m working on other features
