### ISSUE TITLE
Set timezone for Current Time Indicator

### ISSUE THREAD

**Issue by Feduch** [schedule-x/schedule-x#575]
Hi! Thanks for the great product!

Please, add timezone param in Current Time Indicator plugin.

If a time zone is specified, then show the current time indicator for the specified time zone

**Comment by tomosterlund** [comment]
Not quite sure what you mean. Can you please use an example where you specify a parameter name, one or two example values and what impact it would have?

Also what exactly is your use case?

for now the library doesn’t have any type of time zone support, not sure if it would make sense to implement it only for the current time indicator before everything else

**Comment by Feduch** [comment]
In the calendar, the user selects a time zone, in the code I change the time zone for events and the calendar displays events in the selected time zone.

The plugin displays the system time in the calendar, i.e. I can’t influence its current time in any way.

**Comment by tomosterlund** [comment]
I would be open to have this feature. If you need it urgently though you might want to consider opening a PR. Otherwise I’ll gladly do it when I have less work to do on the premium plugins

**Comment by tomosterlund** [comment]
Built this now. Will be included in the next release :) 

thanks for opening the issue!
