### ISSUE TITLE
How to set firstDayOfWeek after calendar is created

### ISSUE THREAD

**Issue by barremob** [schedule-x/schedule-x#581]
When using the viewWeek it is possible to set the number of days with nDays.
However this will used the firstDayOfWeek to start. 
This could change however, sometimes it is monday, tuesday or thursday and friday.
But I can't seem to set the firstDayOfWeek after the calendar was created.

I'm using the @schedule-x/vue, with events-service and calendar-controls.

**Comment by tomosterlund** [comment]
This is currently not possible, but certainly doable.

To make it happen, we need to turn `firstDayOfWeek` in the internal config object into a signal. That way, one could make changes to it via a plugin and reactively update the calendar UI.

**Comment by tomosterlund** [comment]
This can now be done by installing @schedule-x/calendar@2.0.0-alpha.0, updating all your plugins to @schedule-x/{pluginName}@2.0.0-alpha.0 and then using the `setFirstDayOfWeek` API of the calendar controls plugin.

I'll try and release a stable release for v2 within the next week or two.

**Comment by barremob** [comment]
Very nice, thanks very much

**Comment by barremob** [comment]
Just tried it out, however did something change with the event service plugins or the way the plugins are loaded?
It seems that the $app and eventsFacade is undefined now for schedule-x/events-service.
This then gives me the error that it cannot read the properties of undefined with (reading 'add').
So it's not possible to add events after load.

Console log plugins 2.0.0-alpha.0
![image](https://github.com/user-attachments/assets/fa1eeaac-5343-4885-8958-7358e4dbe159)

All I changed so far is the version to 2.0.0-alpha.0, everything else is the same.

Before with 1.63.1
![image](https://github.com/user-attachments/assets/13ba3c32-fc47-4828-86b8-5793a2ddf168)

**Comment by tomosterlund** [comment]
Oh I'm sorry, with Vue this will not yet work. There are a couple of things I'd need to update, that I didn't think of earlier. Sorry for that!

Then keep an eye out for the v2 release. I think I should be able to push it next week :)

**Comment by barremob** [comment]
No problem and no rush from my side.
Very grateful and thanks for the effort already.

**Comment by barremob** [comment]
I tried with version 2.2.0 now, and it looks all working nicely now.

Many thanks for everything 😄

**Comment by tomosterlund** [comment]
Glad to hear 🎉
