### ISSUE TITLE
How to create events?

### ISSUE THREAD

**Issue by marco-scoppetta** [schedule-x/schedule-x#589]
Hi folks, thanks so much for this library,
it looks like it might be very useful also for my project, my (probably silly) question is:

how am I supposed to create events?

I thought it would be possible to click/drag and drop like Google Calendar, but even after adding the D-N-D plugin nothing happens when I click on the calendar (I'm using Week view).

Sorry for the noobish question, but please do enlighten me if possible.

**Comment by marco-scoppetta** [comment]
Nevermind, I guess it requires using the Events Service Plugin to programmatically add event on click. Thanks, sorry for the noise!

**Comment by tomosterlund** [comment]
> Nevermind, I guess it requires using the Events Service Plugin to programmatically add event on click and requires the Premium plugin to drag-to-edit time. Thanks, sorry for the noise!

Completely correct! No worries, glad you figured it out 😊
