### ISSUE TITLE
Bugs using catalan

### ISSUE THREAD

**Issue by alexandearko** [schedule-x/schedule-x#593]
Thank you for wanting to take the time to report a problem. In order to increase the chances of the issue being 
resolved,
please take a moment to give as much relevant information as possible.

**Context:**

- Browser: chrome
- Browser-version: 127.0.6533.88
- Schedule-X version 1.58.0

**Describe the bug**

When I try to use the Catalan language, some text remains in English. and the small calendar should show the days like the big calendar, instead it just shows "d".

Set "local: ca-ES"

![image](https://github.com/user-attachments/assets/524069f0-87e6-49ea-bd2d-1e181066d4fe)

![image](https://github.com/user-attachments/assets/b98acf10-1ac7-4816-80b2-a09b77911478)

**Comment by tomosterlund** [comment]
I saw now, the translations are missing in `packages/translations/src/index.ts` in the PR: https://github.com/schedule-x/schedule-x/pull/590/files
