### ISSUE TITLE
Ability to update dayBoundaries

### ISSUE THREAD

**Issue by mourad1081** [schedule-x/schedule-x#596]
**Is your feature request related to a problem? Please describe.**  
My users don't have the same working hours. Some start working at 6AM, others start at 10AM and finish at 7PM, etc.

**Describe the solution you'd like**  
I'd like to be able to update the dayBoundaries config via a method or something like that.

**Additional context**  

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by mourad1081** [comment]
Thank you for your response, I've found a different workaround (using vuejs) but I'll give a try to your approach

**Comment by pezexd** [comment]
> Thank you for your response, I've found a different workaround (using vuejs) but I'll give a try to your approach

Hello, can you provide me how you handled it with vuejs?

**Comment by NewEraCracker** [comment]
@mourad1081 Can you tell us your solution?

**Comment by mourad1081** [comment]
@NewEraCracker , @pezexd 


I simply forced the agenda to re-create and re-render. It is extremely ugly. I had no time to spend on creating a new plugin as it would require me to learn the internals of this library. (I also went against the documentation and created the calendar in the onMount() lifecycle method as I needed it to be reactive despite the warning. Now that I have time, I will perhaps spend some time to create a plugin.

Here's an example of what I did:


```vue
<template>
  <main>
    <ScheduleXCalendar v-if="render_component" :calendar-app="calendar_app" />
    <button @click="handle_update_settings({start: '09:00', end: '18:00'})">
      Change dayBoundaries
    </button>
  </main>
</template>

<script>

export default defineComponent({
  ...
  setup() {
    return {
      ScheduleXCalendar,
    }
  },
  mounted() {
    this.calendar_app_creator = (override_config = {}) => shallowRef(createCalendar({
      ...
      dayBoundaries: {start: '06:00', end: '22:00'},
      ...override_config
    }));
    
    this.calendar_app = this.calendar_app_creator();
  },

  data() {
    return {
      ...
      render_component: true,
      calendar_app_creator: null,
      calendar_app: null,
    }
  },
  methods: {
    async force_rerender() {
      this.render_component = false;
      // Wait for the change to get flushed to the DOM
      await this.$nextTick();
      this.render_component = true;
    },
    handle_update_settings({start, end}) {
      this.calendar_app = this.calendar_app_creator({
        ... // all the necessary configs for your agenda
        dayBoundaries: {start, end},
      });

      this.force_rerender();
    },
  }
})

</script>

```

**Comment by tomosterlund** [comment]
@mourad1081 no need to go ahead and build a plugin for this, there is a PR linked to this issue which is almost finished, and will close this issue

**Comment by mourad1081** [comment]
Awesome, thank you!
