### ISSUE TITLE
Function to update calendar component

### ISSUE THREAD

**Issue by CindyFMX** [schedule-x/schedule-x#598]
I am trying to create filter for the calendar events as well as updating the event details. However, the new update does not reflect directly to the calendar. I need to refresh first in order to see the new updates.

It will be cool if there is a function that when I call it, the web immediately update the calendar component only. As it might be weird if need to refresh the whole page.

Im using the @schedule-x/vue. Hope this can be developed as soon as possible. I really appreciate it.

**Comment by tomosterlund** [comment]
The configuration object is immutable. You need to use the events service to update events:

https://schedule-x.dev/docs/calendar/plugins/events-service
