### ISSUE TITLE
Many warnings after installation

### ISSUE THREAD

**Issue by adelatatar** [schedule-x/schedule-x#602]
**Hi, thanks for this library, it is awesome.**

**I managed to install and to use the last version of this library, but in the console I have 41 weird warnings and I did not manage to solve them (my project is in react).**

**Here is one of them, the rest are similar:**
WARNING in ./.yarn/cache/@schedule-x-theme-default-npm-1.58.1-f916e16b12-4c26cc8faf.zip/node_modules/@schedule-x/theme-default/dist/index.css (./.yarn/__virtual__/css-loader-virtual-50f93cc229/0/cache/css-loader-npm-6.8.1-30d84b4cf1
-7c1784247b.zip/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./.yarn/__virtual__/postcss-loader-virtual-933a832377/0/cache/postcss-loader-npm-6.2.1-45828eb0de-e40ae79c3e.zip/node_modules/postcss-loader/di
st/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./.yarn/__virtual__/source-map-loader-virtual-3c12a3cdf2/0/cache/source-map-loader-npm-3.0.2-6e868d7f08-d5a4e2ab19.zip/node_modules/source-map-loader/dist/cjs.js!./.yarn/cache/@schedule
-x-theme-default-npm-1.58.1-f916e16b12-4c26cc8faf.zip/node_modules/@schedule-x/theme-default/dist/index.css)
Module Warning (from ./.yarn/__virtual__/source-map-loader-virtual-3c12a3cdf2/0/cache/source-map-loader-npm-3.0.2-6e868d7f08-d5a4e2ab19.zip/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'myProjectPath\client\.yarn\cache\@schedule-x-theme-default-npm-1.58.1-f916e16b12-4c26cc8faf.zip\node_modules\@schedule-x\theme-default\src\components\calendar\
current-time\index.scss' file: Error: ENOENT: no such file or directory, open '/node_modules/@schedule-x/theme-default/src/components/calendar/current-time/index.scss'

**The rest of them are similar, only the file that tries to open is different ('/calendar-header.scss', 'wrapper.scss' etc)**

**First warning that appears is a little different because it refers to autoprefixer:**
WARNING in ./.yarn/cache/@schedule-x-theme-default-npm-1.58.1-f916e16b12-4c26cc8faf.zip/node_modules/@schedule-x/theme-default/dist/index.css (./.yarn/__virtual__/css-loader-virtual-50f93cc229/0/cache/css-loader-npm-6.8.1-30d84b4cf1
-7c1784247b.zip/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./.yarn/__virtual__/postcss-loader-virtual-933a832377/0/cache/postcss-loader-npm-6.2.1-45828eb0de-e40ae79c3e.zip/node_modules/postcss-loader/di
st/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./.yarn/__virtual__/source-map-loader-virtual-3c12a3cdf2/0/cache/source-map-loader-npm-3.0.2-6e868d7f08-d5a4e2ab19.zip/node_modules/source-map-loader/dist/cjs.js!./.yarn/cache/@schedule
-x-theme-default-npm-1.58.1-f916e16b12-4c26cc8faf.zip/node_modules/@schedule-x/theme-default/dist/index.css)
Module Warning (from ./.yarn/__virtual__/postcss-loader-virtual-933a832377/0/cache/postcss-loader-npm-6.2.1-45828eb0de-e40ae79c3e.zip/node_modules/postcss-loader/dist/cjs.js):
Warning

(1240:3) autoprefixer: start value has mixed support, consider using flex-start instead

**I discovered that if I delete: import '@schedule-x/theme-default/dist/index.css' all of my warnings disappear, but of course the scheduler does not look as it should. Also, all warnings mention something about opening '/node_modules/@schedule-x/theme-default/src/.....' but the src folder does not exists in the parent folder.**
**To can use this despite of all these warnings, I set the build to ignore all warnings.**

**Can you tell me what could be the problem here?**

**Comment by adelatatar** [comment]
Thanks for your answer! 

Yes, I managed to make the application work, but only after I set it to ignore all warnings during the build

**Comment by adelatatar** [comment]
Also, what do you think about autoprefixer warning?
(1240:3) autoprefixer: start value has mixed support, consider using flex-start instead

Is there something I ca do to solve it?

**Comment by tomosterlund** [comment]
Thanks for asking :) 

I'm open to PRs for this. I think you'd just need to exchange the one declaration for the other
