### ISSUE TITLE
Docs: all explicit dependencies should be added explicitly

### ISSUE THREAD

**Issue by klao** [schedule-x/schedule-x#608]
**Context:**

- Using schedule-x calendar as a (react, angular, etc.) component by following the docs
- And using a different package manager, like `pnpm`

**Describe the bug**

In https://schedule-x.dev/docs/frameworks/angular (and for other components) the description says to `npm install` two dependencies: `@schedule-x/angular` and `@schedule-x/theme-default`. But then, in the code, you also need to import things from `@schedule-x/calendar`. This is conceptually incorrect. You should not implicitly depend on packages, just because you know they are dependencies of your other dependencies, but instead add them explicitly.

Relying on this mostly works if you are using vanilla `npm`, but does not work with other package managers, for example `pnpm` (which is great to speed things up and save on disk space). `pnpm` _will_ download all transitive dependencies, but will not put them into your `node_modules`, but only into the `node_modules` of the packages that need those dependencies. So, omitting `@schedule-x/calendar` will not work if you are using `pnpm` (but does work with the regular `npm`).

**To Reproduce**

1. Create a fresh angular project with `pnpm` (`ng new --package-manager=pnpm sx-cal-test`).
2. Follow the instructions at https://schedule-x.dev/docs/frameworks/angular, replacing `npm install` with `pnpm install`.
3. The project will not build.

**Expected behavior**

Following the official instructions should work even if one uses a slightly unconventional package manager. 😅

**Comment by tomosterlund** [comment]
But the docs also say:

> If you're using a package manager that does not automatically download peer dependencies, you will additionally need to install @schedule-x/calendar, @preact/signals and preact. This is for example the case for yarn and npm < v7.

If you do so: doesn't it work then?

However, for simplicity, I think it might be a good idea to re-export the views from @schedule-x/angular and thus bundle the calendar with the angular package. What do you think?

**Comment by klao** [comment]
Ok, I looked more into this and I don't understand what's happening. If I understand `pnpm` documentation correctly, it should have worked without me needing to add `@schedule-x/calendar` explicitly. But it didn't. (`pnpm` has a config option `auto-install-peers`, which is true by default, but even setting it explicitly does not change anything.)

I have a guess that this behavior might be triggered by `@schedule-x/angular` having an _exact_ version specified for `@schedule-x/calendar`, but why would it behave differently in that case, I don't know… But this seems like a `pnpm` bug and not related to your libraries. So, feel free to close this issue, and sorry for the confusion! I misunderstood the situation.

> However, for simplicity, I think it might be a good idea to re-export the views from @schedule-x/angular and thus bundle the calendar with the angular package. What do you think?

Yeah, this might make the simplest use-case work without any confusion. But I also don't think that it's really necessary.

**Comment by klao** [comment]
Ok, no, `pnpm` is working as intended. It's just I don't quite understand what's the intention there. 😅

With the `auto-install-peers=false` and `strict-peer-dependencies=false`, `pnpm install` fails in my package. Complaining about all three: `@schedule-x/calendar`, `@preact/signals`, and `preact`. But, if I set `auto-install-peers=true`, all three do get installed, but in a way that they are _only_ accessible to the packages where they are required, but _are not_ exposed to my package. (`pnpm` does some magic with uniquely specified package directories and only links things under `node_modules`, that's how it can save a lot of disk space, same dependencies are shared across projects).

And this behavior seems to be very intentional. If you want to `import` something from a package, you should depend on it explicitly.

**Comment by klao** [comment]
Also, `@schedule-x/angular` having an exact version (`1.59.0`) specified as a peer dependency of `@schedule-x/calendar`, now forces me to also have an exact version of `@schedule-x/calendar` in my `package.json`. Otherwise `pnpm` issues a warning (or fails if `strict-peer-dependencies=true`), which I think is a correct behavior, otherwise there might be a version mismatch.

This, imo, should be loosened in `@schedule-x/angular`.

**Comment by tomosterlund** [comment]
Thanks for doing the research!

I agree, it sounds like it would make sense to loosen up the dependency, probably for all framework-components. I'll start with the angular one only, to see that the renovate updates work the way I expect them to
