### ISSUE TITLE
Make gridHeight changeable without rerendering the whole calendar

### ISSUE THREAD

**Issue by FFabiTM** [schedule-x/schedule-x#619]
**Is your feature request related to a problem? Please describe.**  
It is pretty inefficient to have to rerender the whole calendar when you are trying to change the gridHeight

**Describe the solution you'd like**  
It would be better if you could just change the gridHeight as a reactive property

**Things that could speed up the process**
Probably this could help you:
https://discord.com/channels/1183076861509632011/1183076861509632014/1277992611386228787

**Comment by tomosterlund** [comment]
This should now work with `setWeekOptions` on the calendar controls plugin.

https://schedule-x.dev/docs/calendar/plugins/calendar-controls#setweekoptionsweekoptions-weekoptions-void
