### ISSUE TITLE
How to use the close method for custom event modal?

### ISSUE THREAD

**Issue by CindyFMX** [schedule-x/schedule-x#620]
I wanted to add a close button in my custom event modal. However, I have no idea to do that as the documentation about that is not really clear. Hope you can assist me, thanks!

**Comment by CindyFMX** [comment]
<template>
  <div>
    <ClientOnly>
      <ScheduleXCalendar :calendar-app="calendarApp">





      </ScheduleXCalendar>
    </ClientOnly>
  </div>
</template>

or can I use something like this for the custom event modal? but how?

**Comment by tomosterlund** [comment]
I added an example here: https://github.com/schedule-x/vue-example/blob/main/src/App.vue
