### ISSUE TITLE
The modal is behind the header

### ISSUE THREAD

**Issue by CindyFMX** [schedule-x/schedule-x#631]
Im using nuxt to develop my project with the corresponding version

![image](https://github.com/user-attachments/assets/ab43c14d-b594-43af-9d1c-083aae3a0753)

It can be seen below that the modal is behind the header
![image](https://github.com/user-attachments/assets/bb68f2da-8ea3-4c5a-9287-c1db313d90a9)

**Comment by tomosterlund** [comment]
I’ll try and fix this today or tomorrow. Meanwhile you could roll back to 1.59.1

thanks for reporting 👍

**Comment by tomosterlund** [comment]
OK, was very uncomplicated. Will release a fix in a moment

**Comment by CindyFMX** [comment]
I am not sure if this will be useful to u, but i think the problem should be in @schedule-x/vue. 

Initially, I rollback all the plugins to 1.59.1, the bug still persist. It only disappear when i roll back my @schedule-x/vue to version 1.53.0

**Comment by tomosterlund** [comment]
It was about the @schedule-x/theme-default dependency. This is fixed in the latest version however
