### ISSUE TITLE
Add `beforeRender` and `onRender` callbacks

### ISSUE THREAD

**Issue by klao** [schedule-x/schedule-x#653]
**Is your feature request related to a problem? Please describe.**
We fetch events from a backend on demand in `onRangeUpdate`. But our initial setup is more complicated, because this callback doesn't fire when the calendar is created, only on subsequent changes.

It would be nice to handle things uniformly, from `onRangeUpdate`.

**Describe the solution you'd like**
I know this was already discussed in #494, but I'd still ask you to consider invoking `onRangeUpdate` immediately.
Or, not immediately, I see that it's purposefully prevented from firing in https://github.com/schedule-x/schedule-x/blob/c7e623a25ff384d9f10cb49be8a01be7dc5f026a/packages/calendar/src/utils/stateful/calendar-state/calendar-state.impl.ts#L26-L28 
And that's correct, it shouldn't fire until everything is initialized, but invoke it immediately after that with `setTimeout` or `requestAnimationFrame`?

Yes, this would be a change in behavior, but for most scenarios I can imagine this would be beneficial or neutral. Right now this can only be done cleanly by using an additional plugin and few lines of code, just to replicate the behavior that `onRangeUpdate` would provide.

Alternative suggestions (which would still make things easier and cleaner):
- a config option which controls this initial call (to preserve compatibility)
- a separate callback (`onInitialRange`?)

This is not a critical thing, just a “nice to have”. So feel free to close this if you don't think it's worthwhile.

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this feature
- [x] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
There is a method on the calendar controls plugin called `getRange`.Would this help simplify your initial setup?

https://schedule-x.dev/docs/calendar/plugins/calendar-controls#getrange--start-string-end-string-

I think the problem that I see with letting `onRangeUpdate ` run immediately is the semantics in it. I think most people would expect a method with the word `update` in, only to run once something updates, but no on initialization.

**Comment by klao** [comment]
> There is a method on the calendar controls plugin called `getRange`.Would this help simplify your initial setup?

That's what we use currently.

> I think the problem that I see with letting `onRangeUpdate` run immediately is the semantics in it. I think most people would expect a method with the word `update` in, only to run once something updates, but no on initialization.

Hmm, yeah, makes sense. I didn't think about it that way.
