### ISSUE TITLE
Defining no maxDate defaults to the end of the next year

### ISSUE THREAD

**Issue by jasonsaayman** [schedule-x/schedule-x#657]
**Context:**

- Browser [All]
- Browser-version [All]
- Schedule-X version [All]

**Describe the bug**

A max date is being set in `packages/date-picker/src/utils/stateful/config/config.impl.ts` for the date picker. This leads to you being unable to scroll past this date with the back and forward buttons.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to the hosted example
2. Click on the forward chevron button until you get to December 2025
3. You will not be able to scroll past December

**Expected behaviour**

I don't know if this is expected, but the docs need to be adjusted if it is.

**Screenshots**

![2024-09-10 13 50 13](https://github.com/user-attachments/assets/dac31095-2c5b-43e0-b579-4f40a0fbb52e)

**Comment by tomosterlund** [comment]
This is a regression.

When I started building the project, there was no max date feature, but I didn't want to render more years than 1 year ahead in the date picker year view by default. Then I added a maxDate feature, and seems like I accidentally used the same default date for that, as for the years rendered in the year view.

Thanks for reporting!

**Comment by jasonsaayman** [comment]
@tomosterlund, which way do you want to go with the fix? I would be prepared to PR; I need to know if you want to update the docs or remove the default and then I will start 😄

**Comment by tomosterlund** [comment]
decided on a slightly different approach:
1) keep min- and max dates in date picker, but increase default to current year + 50.
2) in v3 introduce breaking change in calendar, where calendar + date picker share a common min- max date per default

**Comment by jasonsaayman** [comment]
awesome thanks so much @tomosterlund
