### ISSUE TITLE
[1.64.0-alpha.0] Crash calling calendarState.setView after calendar has loaded

### ISSUE THREAD

**Issue by ZacxDev** [schedule-x/schedule-x#670]
Thank you for wanting to take the time to report a problem. In order to increase the chances of the issue being 
resolved,
please take a moment to give as much relevant information as possible.

**Context:**

- Browser [e.g. chrome, safari] brave
- Browser-version latest (1.69.153)
- Schedule-X version [e.g. v1.1.0] Please make sure that you've tried the latest version before reporting the bug.
-1.64.0-alpha.0 (on latest stable version it works fine)

**Describe the bug**

A clear and concise description of how the bug appears to you.
when changing the view using a plugin after the calendar has loaded, i get the following error:

```
preact.module.js:1 Uncaught InvalidDateTimeError: Invalid date time specification: NaN-NaN-NaN 09:00
    at toJSDate (core.js:24:1)
    at getMonthAndYearForDateRange (core.js:1019:1)
    at Object.eval [as __] (core.js:1042:1)
    at B (hooks.module.js:1:3326)
    at Array.forEach (<anonymous>)
    at j (hooks.module.js:1:2087)
toJSDate @ core.js:24
getMonthAndYearForDateRange @ core.js:1019
eval @ core.js:1042
B @ hooks.module.js:1
j @ hooks.module.js:1
setTimeout
r @ hooks.module.js:1
requestAnimationFrame
w @ hooks.module.js:1
c.diffed @ hooks.module.js:1
preact__WEBPACK_IMPORTED_MODULE_0__.options.diffed @ compat.module.js:1
eval @ signals.module.js:1
O @ preact.module.js:1
[...lots of internal preact/reactdom layers]
core.js:24 Uncaught (in promise) InvalidDateTimeError: Invalid date time specification: NaN-NaN-NaN
    at toJSDate (core.js:24:1)
    at eval (core.js:4083:285)
    at Array.map (<anonymous>)
    at b.WeekWrapper [as constructor] (core.js:4083:285)
    at b.q [as render] (preact.module.js:1:9335)
    at O (preact.module.js:1:6526)
    at P (preact.module.js:1:1441)
````

**To Reproduce**

call calendarState.setView after the calendar has loaded.  snippets:

```
class ThreeDayPlugin {
  name = '3-day';
  app: CalendarAppSingleton | null = null;

  init($app: CalendarAppSingleton) {
    this.app = $app;
  }
}
const plugin = new ThreeDayPlugin();

// ...
useNextCalendarApp({
plugins: [plugin]
// ...
})

useEffect(() => {
  if (isThreeDayView) {
  if (plugin.app) {
    plugin.app.config.weekOptions.nDays = 3;
    plugin.app.config.firstDayOfWeek = dayjs(date).day();
    plugin.app.calendarState.setView('week', dayjs(date).format('YYYY-MM-DD'));
  }
}
}, [view])
```

I am trying to use the latest release from today to access the reactive firstDayOfWeek config value feature, as I am trying to implement a 3-day view for the calendar.

**Expected behavior**

**Screenshots**

**Comment by tomosterlund** [comment]
Thanks a lot for reporting. You probably just saved me from releasing breaking changes as a minor version 😊 I forgot, but the changes of that alpha version break any implementation that has custom plugins accessing config options

I think I will take the opportunity to finally ship v2 along with a few other breaking changes I had in mind.

Meanwhile you could just downgrade to 1.63.1

**Comment by lkochniss** [comment]
Hey @ZacxDev,

we implemented a three-days view by using the calendarControls like this:

```
 calendarControls.setWeekOptions({
      ...calendarControls.getWeekOptions(),
      nDays,
    })
```

**Comment by tomosterlund** [comment]
v2 is out now. I wrote a migration guide, on updates in the plugin API: https://schedule-x.dev/docs/migration-v2

That should help you update any custom plugins if you have any others
