### ISSUE TITLE
Show event titles on Mobile View

### ISSUE THREAD

**Issue by KellsWorks** [schedule-x/schedule-x#673]
Hello,

Would it be possible to add event titles on the mobile view? If the titles are too long, they could be truncated or wrapped with ellipses. Currently, only dots are displayed, as shown below.

![Screenshot from 2024-09-18 13-42-21](https://github.com/user-attachments/assets/78a56e6e-92ac-472e-a4c8-0828dd592d2d)

**Comment by tomosterlund** [comment]
If you don't see any event titles in the month agenda, then you don't give the calendar enough vertical space. Try inrceasing the height, and then you will see the events at the bottom.

<img width="313" alt="Bildschirmfoto 2024-09-18 um 16 24 43" src="https://github.com/user-attachments/assets/3d4e8096-b411-45b7-bf10-0c49a74d09d7">
