### ISSUE TITLE
Span is rendered in Month agenda view

### ISSUE THREAD

**Issue by mattskinosix** [schedule-x/schedule-x#678]
Thank you for this incredible component. In these days I have noticed the bug described here:

**Context:**

- Browser-version
- Schedule-X version 1.28
**Describe the bug**

<span> tag is rendered in monthly agenda view 

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Month agenda view'
2. See error

**Expected behaviour**
<span> tag is NOT rendered in the monthly agenda view 

**Screenshots**

![image](https://github.com/user-attachments/assets/371b28da-5352-49f2-8434-bb0f2c9cfed1)

**Comment by tomosterlund** [comment]
Fixed, and will be released as part of v2.0.0 next week. Meanwhile you could roll back to the version before this error

**Comment by mattskinosix** [comment]
For Vue users "@schedule-x/vue": "1.54.1" is not affected by this bug
