### ISSUE TITLE
inputDisplayedValue format to dd.mm.yyyy

### ISSUE THREAD

**Issue by reccashi28** [schedule-x/schedule-x#709]
**Is your feature request related to a problem? Please describe.**  
is there a way to format the datePickerState inputDisplayedValue  to dd.mm.yyyy. At the moment, the format for german date is d.m.yyyy

**Comment by tomosterlund** [comment]
Could add the possibility to configure the Intl options used for the input, and then you can just use the native browser API for this 😊

**Comment by tomosterlund** [comment]
I won't implement this myself, but I'd be open for PRs that achieve this
