### ISSUE TITLE
All day events from ICS show up as spanning an extra day beyond the range end

### ISSUE THREAD

**Issue by justin-hackin** [schedule-x/schedule-x#722]
**Context:**

See reproduction

**Describe the bug**

All day events show up as spanning an extra day beyond the range end.

**To Reproduce**

You can open up  [this repository](https://github.com/justin-hackin/schedule-x-ics-allday-repro) in stackblitz to see the issue. The ics string is an unadulterated export from a google calendar.

**Expected behavior**

The single day all day event shows up as spanning 1 day, not 2.

**Comment by justin-hackin** [comment]
You can see from the ICS text that the range is only specified by date but then when you click on the event, the console logs indicate that the range is given a time of midnight. This makes it difficult to disambiguate date-time ranges from all-day ranges. The fullcalendar event representation has a boolean value isAllDay which is quite useful for this case and I would suggest adopting this convention.

**Comment by justin-hackin** [comment]
This issue becomes much more severe if you use the `dayBoundaries` feature. With `dayBoundaries: { start: "09:00", end: "03:00" }` the event becomes a tiny fragment on week view:

<img width="1025" alt="Screenshot 2024-10-07 at 10 51 42 AM" src="https://github.com/user-attachments/assets/8b9b6b4b-a072-4e90-b0ac-32c43065316f">

and it disapears alltogether on day view 😬

**Comment by justin-hackin** [comment]
I'm pretty sure I see what the problem is here. I noticed 1 day all day events in scheduleX start and end on the same day and don't have a time which is not consonant with the ICS spec as I described above.

**Comment by tomosterlund** [comment]
Decision from chat & PR:

We will infer events starting and ending on midnight, to be all day events, and to subtract 1 day from the date end.

Since an single-day all-day event in Schedule-X has the format: `{ start: '2024-10-09', end: '2024-10-09' }` subtracting one day from the end is needed to match RFC5455 where a single-day full-day event would look like:

```
DTSTART:20100101T000000
DTEND:20100102T000000
```

or

```
DTSTART;VALUE=DATE:20241025
DTEND;VALUE=DATE:20241026
```
