### ISSUE TITLE
createEventsServicePlugin set(events) is giving error: TypeError: Cannot read properties of undefined (reading 'set') 

### ISSUE THREAD

**Issue by pdeva03** [schedule-x/schedule-x#725]
I am trying to set calendar events in my vue3 application using createEventsServicePlugin(@schedule-x/events-service) but getting below error.

**TypeError: Cannot read properties of undefined (reading 'set')**

**Calendar setup:**
const calendarControls = createCalendarControlsPlugin();
const eventModal = createEventModalPlugin();
const eventsServicePlugin = createEventsServicePlugin();

const calendarApp = shallowRef(createCalendar({
  firstDayOfWeek: 0 ,
  locale: locale.value,
  views: [viewWeek],
  defaultView: viewWeek.name,
  plugins: [
    eventsServicePlugin,
    eventModal,
    createScrollControllerPlugin({
      initialScroll: '05:50'
    }),
    calendarControls,
  ],
}))

eventsServicePlugin.set(events) is giving the error. Same with adding single event(eventsServicePlugin.add(event)) as well.

**Comment by tomosterlund** [comment]
Thanks for opening this issue. This is the same issue as in: https://github.com/schedule-x/schedule-x/issues/713

Can you post all relevant dependencies + their versions from your package.json?

**Comment by pdeva03** [comment]
I migrated to version 2 of all packages and it started working for me. Thank you!
