### ISSUE TITLE
In the Drag-and-Drop plugin, add the possibility to copy an event by pressing <Ctrl> when we drag it

### ISSUE THREAD

**Issue by harry-73** [schedule-x/schedule-x#728]
**Is your feature request related to a problem? Please describe.**  
When we drag an event, it is frustrated to not be able to copy it. The only possibility is to move it

**Describe the solution you'd like**  
Pressing the crtl key when we drag an event should duplicate the event.

**Additional context**  

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [X] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

**Comment by harry-73** [comment]
On Outlook, it like like that: We drag to move an event and press ctrl key to copy it.

If we use crtl+v, we'll have to open a modal window to allow the user to set the dates. I don't like this very much.

My vision is the following:

- for quick copy/duplication, use the mouse/touch and the crtl key in day/week/month view
- if you need more (change title, description or copy outside the current view), use the event's modal window with a duplicate button 'à la' Google calendar

**Comment by HunterLiddell** [comment]
While I'm not adding any insight or opinion to this issue, I just want to say that this QoL feature would be fantastic. Hopefully this is something truly considered as I'd find use from it as well!

**Comment by tomosterlund** [comment]
Closing this due to breaking changes added in the PR. Would be open to a PR that does not introduce any breaking changes

**Comment by starredev** [comment]
@harry-73 I made an plugin which is exactly doing this

https://github.com/starredev/schedule-x-plugins
