### ISSUE TITLE
Custom html in modal with the event-modal plugin

### ISSUE THREAD

**Issue by HunterLiddell** [schedule-x/schedule-x#733]
Not sure I am filling this out correctly, so feel free to ask for clarification or additional info!

**Is your feature request related to a problem? Please describe.**  
There is not a problem with the library itself, just looking for a new feature.

**Describe the solution you'd like**  
As a developer, I'd like to use this modal as a way to edit or delete an event since there isn't any other nice way of doing it in my case - continue reading as I know this statement might be odd. After clicking an event and opening the modal it would be great to place my own html inside. My use-case is adding two buttons inside to interact with. I wouldn't need these buttons or any of the html to interact directly with the event, but only to tie these buttons to each event.

This would of course require a way to handle the fired events from clicking buttons. In my case, this would allow me to utilize an edit and delete button directly on the CalendarEvents for my custom use-case.

Not sure if this is to be included, but having additional options for the modal such as choosing what to display (title, DateTimes, etc) would approve this feature as I could remove/add the CalendarEvent data at will.

**Additional context**  
Note that my usage of this library is not that of a normal calendar. I'm using the calendar to schedule events, but each event has significantly more data that I am handling on my end, so the premium interactive event modal is not of use to me.

**Things that could speed up the process**
- [✔️] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
Hi there,

I see three ways you can achieve what you need:

1) **the hacky way**. There is a slot/custom component if you're using any of the framework adapters. With the `eventModal` custom component you can take control over the content in the modal. This in itself is not hacky. The hacky part though, is that the open sourced modal is not designed to ever be an interactive one, and it will close automatically whenever it detects a click outside. So this won't play nicely with using dropdowns and popups with teleport features for your form. Probably you could hack your way around this though.

2) **the 100% custom way** you could detect clicks on events with the callback `onClickEvent` and then use that callback as a trigger to open the modal

3) **the paid way** you can add custom fields to the interactive event modal. It might not support all data types atm, but I'm more than willing to extend this on request

**Comment by HunterLiddell** [comment]
Ah I did not see that the paid feature has custom fields, I only assumed it was set with the basic event reoccurrence fields that you'd find in most calendars. Unfortunately, my data is pretty drastic compared to what you would want to support, so I will have to go with my own methods to do this. 

Thank you for the response!
