### ISSUE TITLE
Multiple Calendar in single Page not working

### ISSUE THREAD

**Issue by nirajraba212** [schedule-x/schedule-x#734]
- Schedule-X version [v1.59.0] 

**Describe the bug**
- When we have configure Schedule-X in VUE 3 custom component. And try to render same component multiple time in single page it's creating issue to switch views.

**To Reproduce**
- Step 1 - Render  custom component with schedule-X multiple time in single page.
- Step 2 - Try to switch views in any one of calendar.
- Step 3 - It will change the view but it will wipe out other calendar and there is no console errors.

**Expected behavior**
- If we change anything in one calendar, It should not affect other calendar component.

**Screenshots**
![image](https://github.com/user-attachments/assets/0960b275-d8d6-486e-8823-780559c6ef02)

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this fix
- [ ] I believe I know how to do this, and am willing to implement the whole thing.
- [x] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
Can you include the code you use for setting up the calendar?

Do you import `viewMonthGrid` or `createViewMonthGrid` from '@schedule-x/calendar'? If the former, that would be the error

**Comment by nirajraba212** [comment]
`feature.config = SXCalendar.createCalendar({
          selectedDate: localYYYYMMDDHmm(new Date()),
          views: [SXCalendar.viewDay, SXCalendar.viewWeek, SXCalendar.viewMonthGrid, SXCalendar.viewMonthAgenda],
          defaultView: SXCalendar.viewWeek.name,
          //initialView: 'timeGridWeek',
          events: feature.events,
          plugins: [ SXResize.createResizePlugin(), SXScrollController.createScrollControllerPlugin({ initialScroll: '07:50' }),
            eventsService, SXEventModal.createEventModalPlugin(), interactiveEventModal, sidebar],
          //plugins: [ScheduleX.createDragAndDropPlugin(), ScheduleX.createResizePlugin(), ScheduleX.createScrollControllerPlugin(), ScheduleX.createEventsServicePlugin(), ScheduleX.createEventModalPlugin()],

          callbacks: {
            /** * Is called when: * 1. Selecting a date in the date picker * 2. Selecting a new view * */
            onRangeUpdate(range) {
              console.log('new calendar range start date', range.start)
              console.log('new calendar range end date', range.end)
            },
            /** * Is called when an event is updated through drag and drop * */
            onEventUpdate(updatedEvent) {
              console.log('onEventClick', calendarEvent)
            },
            /** * Is called when an event is clicked * */
            onEventClick(calendarEvent) {
              console.log('onEventClick', calendarEvent)
            },
            /** * Is called when clicking a date in the month grid * */
            onClickDate(date) {
              console.log('onClickDate', date) // e.g. 2024-01-01
            },
            /** * Is called when clicking somewhere in the time grid of a week or day view * */
            onClickDateTime(dateTime) {
              console.log('onClickDateTime', dateTime)
            },
            /** * Is called when clicking the "+ N events" button of a month grid-day * */
            onClickPlusEvents(date) {
              console.log('onClickPlusEvents', date) // e.g. 2024-01-01
            },
            /** * Is called when the selected date is updated * */
            onSelectedDateUpdate(date) {
              console.log('onSelectedDateUpdate', date)
            }
          },
          calendars: feature.calendars || {},
          guid: feature.guid
        });
        
        setTimeout(() => { feature.config.render(document.querySelector('.a' + feature.guid + ' #schedule-calendar')); }, 100);`

**Comment by tomosterlund** [comment]
You need to use the factory functions for creating the view, like `createViewMonth`, or `createViewWeek` if you use multiple calendars.

And I need to update the docs for using CDN I see now 😊

**Comment by nirajraba212** [comment]
I tried with only Day and Week with below code still getting same issue.. can we connect on Discord? I sent you request.

**Comment by nirajraba212** [comment]
ok got working with factory functions thanks.
