### ISSUE TITLE
Sticky calendar header

### ISSUE THREAD

**Issue by Bl00D4NGEL** [schedule-x/schedule-x#742]
**Is your feature request related to a problem? Please describe.**  
Whenever a user (on a smaller screen) scrolls down on a page with the schedule-x calendar the header (that shows the date/weekday) does not follow (isn't sticky)

**Describe the solution you'd like**  
On an ideal world there would be config option to make those headers sticky (and, in a perfect world one would be able to configure what to keep showing e.g. only show the number or only day of week or both).

This config option should ideally be reactive but must not be if the overhead is too high (or a BC break would be required)

**Additional context**  
None as far as I'm concerned

**Things that could speed up the process**
- [X] I can picture implementing at least parts of this feature
- [X] I believe I know how to do this, and am willing to implement the whole thing.
-> This is already part of our backlog and quite high in it as well so we might get around implementing this in ~2-4 weeks ourselves
- [ ] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
Which view are you talking about here?

In the day/week views there is a sticky header

https://github.com/user-attachments/assets/310735fd-fa4d-47ba-b427-98261d68b3bd

**Comment by tomosterlund** [comment]
Closing for now, but we can reopen if you still need this and I understand what it's about :)
