### ISSUE TITLE
Update Dutch translations.

### ISSUE THREAD

**Issue by YannickWhorst** [schedule-x/schedule-x#744]
Thank you for wanting to take the time to report a problem. In order to increase the chances of the issue being 
resolved, please take a moment to give as much relevant information as possible.

**Context:**

- All browsers
- Version [v2.4.1](https://github.com/schedule-x/schedule-x/releases/tag/v2.4.1)

**Describe the bug**

I have noticed that some of the [Dutch translations](https://github.com/schedule-x/schedule-x/pull/281) that I have added, weren't correct.

I have also noticed that `Select View` is in the `date-picker.ts` translation file, but is not used in the `date-picker` at all, it is used in the `calendar` (this might be expected, but I am just not aware of it).

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this fix
- [x] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
That seems wrong with the “Select view” text. I can add a commit for this
