### ISSUE TITLE
WeekView  not available for SmartPhone

### ISSUE THREAD

**Issue by harry-73** [schedule-x/schedule-x#748]
**Is your feature request related to a problem? Please describe.**  
WeekView  not available for SmartPhone

**Describe the solution you'd like**  
Why it is not possible to have weekView for SmartPhone. I think, by default, it should be available and after, the choice to allow it is at the developer / application level 

**Additional context**  

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this feature
- [x] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
I deliberately chose to not make week view mobile compatible, for the simple reason that I think it looks too crammed.

If you want to override this, you can set the `hasSmallScreenCompat` property of the week view to `true`, and then you might have to write some custom styles to make it look reasonable on mobile

**Comment by manuelmeister** [comment]
How do you override the property?
