### ISSUE TITLE
Sync with other calendars

### ISSUE THREAD

**Issue by Omicrxn** [schedule-x/schedule-x#749]
Hi! I was wondering if maybe calendar sync with other providers such as Google or Outlook is on the roadmap. Like they all have their API's but maybe a way to simplify this process internally by schedule-x would be cool.

**Comment by tomosterlund** [comment]
Hey there!

This is currently not on the roadmap for me. I'd be open to anyone wanting to write a plugin for this, but I don't see myself building this anytime soon.
