### ISSUE TITLE
Validate date and date time for events

### ISSUE THREAD

**Issue by rsslldnphy** [schedule-x/schedule-x#751]
**Context:**

- Browsers: Chrome Version 130.0.6723.92 (Official Build) (arm64) and safari Version 18.0.1 (20619.1.26.31.7)
- Schedule-X version [e.g. v1.1.0] Please make sure that you've tried the latest version before reporting the bug.
- 2.4.1

**Describe the bug**

Multi day events are not showing on the Day on Week views, only the Month view. (this feels more likely to be a misunderstanding on my part than a bug so apologies in advance for that.

**To Reproduce**

I've created an empty remix app (`pnpx create-remix@latest`) and added the smallest subset of code I can make that reproduces the problem. This is the relevant calendar code:

```typescript
import {
  viewDay,
  viewMonthAgenda,
  viewMonthGrid,
  viewWeek,
} from "@schedule-x/calendar";
import { ScheduleXCalendar, useCalendarApp } from "@schedule-x/react";
import "@schedule-x/theme-default/dist/index.css";
import { addDays } from "date-fns";

export default function Index() {
  const events = [
    {
      id: "f-0",
      title: "foo",
      description: "foo event",
      start: new Date().toISOString(),
      end: addDays(new Date(), 1).toISOString(),
    },
  ];
  const calendar = useCalendarApp({
    views: [viewDay, viewWeek, viewMonthGrid, viewMonthAgenda],
    events,
  });

  return (
        <ScheduleXCalendar calendarApp={calendar} />
  );
}
```

**Expected behavior**

Expected to see the multi-day event on all three views.

**Screenshots**

Day view:
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/34bcfd0a-c8e9-44cf-9b62-61036a0d5fd6">

Week view:
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/2c187b14-05eb-42bb-bc31-06ce3fef0dc8">

Month view:
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/0c24f430-fc3a-49a4-a2bf-7d3c7567fa1a">

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this fix
- [ ] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

...adding my own:

- [X] Assessing Schedule-X with the intention of buying a premium licence for the resource scheduler functionality

**Comment by rsslldnphy** [comment]
ok it looks like a date format issue. i was using `date.toISOString()` which formats dates like this: `'2024-11-05T09:17:27.287Z'`. if i change the dates to this: `'2024-11-05 09:17'` all three views work.

leaving this issue open for now as it feels like inconsistent behaviour for it to work on the monthly view but not on the daily or weekly - and for it to not throw an error when given a date in an invalid format. 

would say that either always working with an ISO date string or always throwing a descriptive error would be good fixes, though my preference would be for the first.

**Comment by tomosterlund** [comment]
I think the library should probably better start throwing errors or at the least output console errors for unsupported date string format.

We can leave this issue open until I’ve added such validation. Thanks for reporting!
