### ISSUE TITLE
Drag and Drop - event "_options" value is always undefined

### ISSUE THREAD

**Issue by zehenrique** [schedule-x/schedule-x#756]
**Context:**

- Browser: Chrome
- Schedule-X version: 2.4.1

**Describe the bug**

When using Drag and Drop to update an event, the updated object does not include the "_options" values. It looks like when the event object is copied, the "_options" values are discarded.

**Expected behavior**

The entire object would be expected to be copied when dragging and dropping.

**Screenshots**
`
  callbacks: { 
    /**
    * Is called when an event is clicked
    * */
    onEventClick(event) {
      console.log(event);
    },
    /**
     * Is called when an event is updated through drag and drop
     * */
    onEventUpdate(updatedEvent) {
      console.log(updatedEvent);
    },
  }
})`

onEventClick() returned object

![1](https://github.com/user-attachments/assets/850fb080-b535-4d15-b25c-218f2fc70288)

onEventUpdate() returned object

![2](https://github.com/user-attachments/assets/91cb5fd4-f3a4-43dc-802f-a23511d7d98a)

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this fix
- [ ] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
Thanks for reporting!

Will add a new patch version
