### ISSUE TITLE
Wrong import in Angular for  "import { JSXInternal } from "preact/src/jsx";

### ISSUE THREAD

**Issue by marcovittoriozacca** [schedule-x/schedule-x#765]
- Schedule-X version:
    "@schedule-x/angular": "^2.3.1",
        "@schedule-x/calendar": "^2.4.3",
        "@schedule-x/calendar-controls": "^2.4.3",
        "@schedule-x/events-service": "^2.4.3",
        "@schedule-x/preact": "^2.3.2",
        "@schedule-x/theme-default": "^2.4.3",

After importing calendar-controls and events-service i get the error: 
    "TS2307: Cannot find module 'preact/src/jsx' or its corresponding type declarations. "
for this line
    "import { JSXInternal } from "preact/src/jsx"

![Screenshot 2024-11-07 alle 10 54 04](https://github.com/user-attachments/assets/b533c35d-bbe8-454d-bf01-30942fa40338)
![Screenshot 2024-11-07 alle 10 54 30](https://github.com/user-attachments/assets/9503eadb-df41-4668-a56e-d94a5a72f069)

**Comment by tomosterlund** [comment]
Which package manager are you using?

Previously, a few users using pnpm or yarn had similar issues, because those package managers don't download peer dependencies per default.

**Comment by marcovittoriozacca** [comment]
> Which package manager are you using?
> 
> Previously, a few users using pnpm or yarn had similar issues, because those package managers don't download peer dependencies per default.

Im using npm

**Comment by marcovittoriozacca** [comment]
I found the error, and now it’s working as it should! The problem was related to how my project was handling the modules. Sorry for the issue.
