### ISSUE TITLE
Add Support for Custom Locales via Config Option in Schedule-X

### ISSUE THREAD

**Issue by coolRoger** [schedule-x/schedule-x#772]
**Is your feature request related to a problem? Please describe.**  
I'm currently using Schedule-X and am finding it inconvenient to add new locales. As it stands, each new locale requires a pull request to the official repository, followed by a waiting period for review and merge. This makes it difficult to add temporary or custom locales efficiently, particularly when quick iterations are needed or when customization is unique to individual implementations.

**Describe the solution you'd like**  
I would like Schedule-X to support a config option that allows users to add or override locale settings dynamically at runtime. For example, this could be accomplished by enabling a locales property within the config. This property would accept an object that defines locale keys and their respective translations, allowing custom locales to be added without modifying the core library or submitting pull requests.

`config: {
  locale: "MS",
  locales: {
    "MS": {
      Today: 'Today',
      Month: 'Month',
      Week: 'Week',
      Day: 'Day',
      'Select View': 'Select View',
      events: 'events',
      event: 'event',
      'No events': 'No events',
      'Next period': 'Next period',
      'Previous period': 'Previous period',
      to: 'to', // as in 2/1/2020 to 2/2/2020
      'Full day- and multiple day events': 'Full day- and multiple day events',
      'Link to {{n}} more events on {{date}}': 'Link to {{n}} more events on {{date}}',
      'Link to 1 more event on {{date}}': 'Link to 1 more event on {{date}}',
      Date: 'Date',
      'MM/DD/YYYY': 'MM/DD/YYYY',
      'Next month': 'Next month',
      'Previous month': 'Previous month',
      'Choose Date': 'Choose Date',
    }
  }
}`

This would allow developers to directly configure and customize locale data as part of their project setup, enhancing flexibility and reducing dependency on the core repository for minor localization adjustments.

**Additional context**  
This feature would be especially beneficial for teams working in multi-lingual environments or for those requiring region-specific terms that aren't universally relevant. Additionally, it could make Schedule-X more adaptable in enterprise settings, where custom localization requirements often need fast implementation.

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
Thanks for opening this issue. Was having a chat with another user last week, where this would have been one of the two possible solutions. Definitely makes sense to implement, just the way you already suggested
