### ISSUE TITLE
Nuxt: Build does not work anymore

### ISSUE THREAD

**Issue by AndreasFaust** [schedule-x/schedule-x#773]
In development everything works as expected. On build and preview there is this error:
```
Named export 'ScheduleXCalendar' not found. 
The requested module '@schedule-x/vue' is a CommonJS module, 
which may not support all module.exports as named exports. 
CommonJS modules can always be imported via the default export, for example using: 
import pkg from '@schedule-x/vue'; const { ScheduleXCalendar } = pkg;
```
The suggested solution produces a different error.

I tried out the example repo (https://github.com/schedule-x/nuxt-example) which does not work, once you update everything to the latest version:
<img width="457" alt="Bildschirmfoto 2024-11-12 um 13 04 30" src="https://github.com/user-attachments/assets/f94a76de-7a90-4127-91c3-747dde1ade17">

The example repo shows this error on build/preview:
```
500
calendarApp cannot be saved in a ref. 
Since this causes deep reactivity, 
it destroys the calendars internal reactivity. 
Save in a normal const or shallowRef
```

**Comment by tomosterlund** [comment]
I need to update the nuxt example. The fix is exactly what the error message says, that `calendarApp`, has to be saved in `shallowRef`.

Let's keep this open as a reminder to me that I need to update that example, but meanwhile in your implementation you can change to `shallowRef`

**Comment by AndreasFaust** [comment]
Thank you for the quick reply, @tomosterlund!
Yes, this fixes the example repo – in dev mode and with build/preview.

I wonder, why it does not work in my other Nuxt project. I am using an NPM version larger than 7 , which downloads peer dependencies. I will try to reproduce it in a code sandbox.

**Comment by tomosterlund** [comment]
Feel free to post more info on it, or open another issue if you discover something that doesn't work as it should

**Comment by AnoRebel** [comment]
Hi, I was having the same error on nuxt but only in production:
```sh
Named export 'ScheduleXCalendar' not found. 
The requested module '@schedule-x/vue' is a CommonJS module, 
which may not support all module.exports as named exports. 
CommonJS modules can always be imported via the default export, for example using: 
import pkg from '@schedule-x/vue'; const { ScheduleXCalendar } = pkg;
```

The suggested solution produces a different error still.

I tried adding the package to be transpiled on build and it seems to be working for now.
```ts
export default defineNuxtConfig({
  build: {
    transpile: ["@schedule-x/vue"],
  },
});
```
