### ISSUE TITLE
Add Dual Alphabet Support (Cyrillic and Latin) for Serbian

### ISSUE THREAD

**Issue by alexva22** [schedule-x/schedule-x#774]
The current implementation of srRS only supports the Latin script, and when adding to the calendar, I encounter an issue with mixing Latin and Cyrillic. The month name is currently written in Cyrillic, while everything else is in Latin.

![Screenshot_2024-11-07_at_14 57 53](https://github.com/user-attachments/assets/a2a346e6-8f07-4f71-b289-f7ae53e04bfb)

**Comment by tomosterlund** [comment]
For documentation, from Discord:

> So we could rename that [srRS] into srLatnRS and add srRS for Cyrillic alphabet translations
