### ISSUE TITLE
Premium features over CDN

### ISSUE THREAD

**Issue by cunninw** [schedule-x/schedule-x#775]
I was wondering if you are able to use the premium features over CDN?

**Comment by tomosterlund** [comment]
To my knowledge, there is so far only one customer of Schedule-X premium, who uses `@schedule-x/calendar` over a CDN. Their solution for using premium was to download the package via npm, but then commit it to version control and host it on their own server, which is fine by me.

I would also be open to hosting the assets of the premium plugins in AWS and distribute via Cloudfront, but I'd have to charge a little extra for hosting costs + extra work.

If you want to have a chat, I have some free time slots here: https://calendly.com/schedule-x/lets-chat
