### ISSUE TITLE
Validate id in event

### ISSUE THREAD

**Issue by vinipetrol** [schedule-x/schedule-x#780]
I'm having a problem with the DND plugin on the week view mode. If I try to dnd an event with moth view mode everything works fine. However, if I'm on week view mode the application crashes doing horizontal DND of an event (vertical DND works fine).

- Browser: Chrome and Firefox
- Browser-version: latest versions
- Schedule-X version: I testes several versions. Same problem in all of them

**To Reproduce**

Create an event with an "ID" being a float number. 

`

    calendar.eventsService.add({

      id: Math.random(), // Example number created: 0.95654564712

      start: dateTimeMoment.format('YYYY-MM-DD HH:mm'),

      end: dateTimeMoment.add(1, 'hour').format('YYYY-MM-DD HH:mm'),

      title: 'Event X',

      location: 'Hospital'
  
    });
`

When you create an event with an "ID" using a float number the DND doesn't work horinzontally on week view mode.

**Expected behavior**

DND works horinzontally on week mode

** Possible solution **

If an "ID" is passed as floating number, add something like `Math.floor` to trim it.

**Screenshots**

![image](https://github.com/user-attachments/assets/6689f797-4b20-4e84-b8b4-776b2ace3547)

**Comment by tomosterlund** [comment]
Should probably be solved together with https://github.com/schedule-x/schedule-x/issues/751

I wouldn't ever modify any user input, since that could lead to some very unexpected behaviors for the implementer/user. What would make sense IMO though is to validate the ids coming in.
