### ISSUE TITLE
Ability to have no end on events

### ISSUE THREAD

**Issue by Xstoudi** [schedule-x/schedule-x#783]
**Is your feature request related to a problem? Please describe.**  
I need to display ponctual events, without time span, only start date.

**Describe the solution you'd like**  
Just be able to ignore `end` field in my event, leading to cleaner display of my event.

**Additional context**  
Currently:
![image](https://github.com/user-attachments/assets/5c358df4-088f-457b-a2e8-4d97cf65e676)

Would prefer:
![image](https://github.com/user-attachments/assets/a05d8cd0-17b2-4ae8-b1ae-4b5ba5d0182a)

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
I'm for it. However, I think for now, the right solution would be to just not display `end` when it equals `start`.

Making `end` non-required will blow up a fair number of things in the library, so I'll have to add it to the list of breaking changes for v3.

**Comment by Xstoudi** [comment]
Yeah, that's what I imagined when looking at the code. Would it be ok if I PR this week?

**Comment by tomosterlund** [comment]
Sure thing!

**Comment by Xstoudi** [comment]
Here it is @tomosterlund : https://github.com/schedule-x/schedule-x/pull/790

Let me know if anything is missing and/or wrong.

**Comment by tomosterlund** [comment]
Thanks again!

This will be included in the next release.
