### ISSUE TITLE
Ability to prevent events from overlapping

### ISSUE THREAD

**Issue by Paperfeed** [schedule-x/schedule-x#792]
**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  
We have a use case where events should never overlap (also when resizing or dragging and dropping for example). 
It would be great if there was a way to "block" an event update based on certain rules.

**Additional context**  
Some points you brought up in the Discord channel:
how to make users aware that they can’t resize/drag until a certain time?
API: define all forbidden hours manually (flexible solution), or automatically forbid all times where there are events (good for your use case but not flexible)
should the forbidden slots only be forbidden under certain circumstances? In other words, should you be able to test conditions for an event to see if it can be resized into a certain time? (Very flexible API, but more complexity added?)

The way I could see this working (without having detailed knowledge of the inner working of this library at this moment) is if there were an option to have a function fire with the previous state of the event and the new state before actually updating the event.

Currently it seems that we have no control over the calendar updating the event. It simply updates and then fires the onEventUpdate callback. I'm imagining something like a onBeforeEventUpdate callback where we can run validation rules and cancel the update (by returning a boolean or whatever) would make this usecase quite simple to implement. 

This is perhaps not entirely related to what I wrote above but:
It seems like the plugin interface is limited to beforeRender and onRender? Is it possible to make a plugin that also hooks into the existing callbacks (like a middleware)?

**Things that could speed up the process**
- [x] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.
- [x] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
> Currently it seems that we have no control over the calendar updating the event. It simply updates and then fires the onEventUpdate callback. I'm imagining something like a onBeforeEventUpdate callback where we can run validation rules and cancel the update (by returning a boolean or whatever) would make this usecase quite simple to implement.

Sounds like a good idea. Then something like this perhaps:

`onBeforeEventUpdate({ before: CalendarEvent, after: CalendarEvent }): boolean`

And return value `false` cancels the update.

> It seems like the plugin interface is limited to beforeRender and onRender? Is it possible to make a plugin that also hooks into the existing callbacks (like a middleware)?

While possible, I'm not sure it's needed. I think if you should be able to do something like this:

```ts
const myCustomPlugin = createMyCustomPlugin()

const calendar = createCalendar({
  callbacks: {
    onRangeUpdate() {
      myCustomPlugin.myCustomMethod
    }
  },
  plugins: [myCustomPlugin]
})
```

**Comment by Paperfeed** [comment]
I'm thinking it might be nice if you can return false to block the update and return a validated event otherwise. 

That way you can adjust the event (eg. if it overlaps, you could trim it in the onBeforeUpdate callback and then return the event with the trimmed DateTime), after which the normal flow would continue. 

Again, I'm just imagining things here without having looked at the inner workings yet. When I have some free time I would be happy to familiarize myself, but I'm pretty swamped at the moment.

**Comment by tomosterlund** [comment]
Cool idea, but I think the simpler option here if you want to update the event to another time instead of aborting, would be to call `update` in the events service. That way the resize plugin can keep having as it's sole focus to just be resizing, and now validating if it's allowed to resize, whereas the events service takes care of all manual updates.
