### ISSUE TITLE
Ripple from default theme interfering with PrimeVue's ripple directive

### ISSUE THREAD

**Issue by tobiasstr** [schedule-x/schedule-x#814]
First of all, I just want to say great project!

**Is your feature request related to a problem? Please describe.**  
I ran into a minor issue when using the default CSS theme in a project which also uses PrimeVue (v3 / Tailwind). Both projects use [the same animation name for ripple](https://github.com/primefaces/primevue/blob/1aa7a026e953cc80e2b9da5d4207e4113983ae4a/packages/primevue/src/ripple/style/RippleStyle.js#L17), but the implementation differ I guess. When directly importing the Schedule-x default theme in a Vue component, PrimeVue's ripple directive stops working after said component is loaded. 

Was a bit confusing at first, when the ripple effect in the rest of my project stopped working at seemingly random times. As Schedule-x is working as expected, I did not submit this as a bug. But I guess in the end it's just a CSS cascading issue, and which project gets issues comes down to which CSS is loaded first.

**Describe the solution you'd like** 
Maybe the animation names related to ripple could simply be prefixed like the other selectors in the default theme? I'm not sure about all the implications or possible solutions here, but that was how I fixed it locally for my project.

The obvious solution is to not use multiple ripple implementations in a single project, but I thought I should mention it anyway. 

**Additional context**  
None

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.
- [ ] I have a Schedule-X premium license

**Comment by tomosterlund** [comment]
Thanks for reporting!

I guess it'd make sense to namespace the animation, just like I namespace most of the classes
