### ISSUE TITLE
Event spanning two days does not display correctly, and modal not opening when clicking on the second day

### ISSUE THREAD

**Issue by iam-sreekanth** [schedule-x/schedule-x#818]
I created an event that spans two days, but the following issues were encountered:

The event shows the start time (11:50 PM) on the first day, but it does not display the end time (12:50 AM) on the second day.
Clicking on the event grid for the second day does not open the event modal. The modal only opens when clicking on the grid for the first day.

Create a multi-day event that starts late on one day and ends early on the next day.
Example:
json
Copy code
{
    "id": "36",
    "title": "Test event",
    "start": "2024-12-16 23:50",
    "end": "2024-12-17 00:50",
    "calendarId": "high",
    "description": ""
}

[
![Screenshot 2024-12-06 224301](https://github.com/user-attachments/assets/1a63c7f5-eae8-4e4c-a762-793bf1851db9)
](url)

The event starts at 11:50 PM on December 16th and ends at 12:50 AM on December 17th.
View the event on the calendar:
The first day shows the start time (11:50 PM).
The second day does not display the end time (12:50 AM).
Click the event grid on the second day:
The modal does not open.

Expected Behavior:-
The event should display the start time on the first day and the end time on the second day.
The event modal should open regardless of whether the event grid for the first or second day is clicked.

Actual Behavior:
The second day does not display the event’s end time.
Clicking on the second day's event grid does not open the modal.

**Environment**

1. Package Version:  "@schedule-x/react": "^2.9.0"
2. TypeScript Version:  "typescript": "^5.5.3"
3. Framework: "react": "^18.3.1"

**Comment by tomosterlund** [comment]
Only displaying the start time is not a bug. I just modeled this after how the Google calendar works, and think I will stick to that decision for now at least. You could use a custom component or custom content if you want to override this.

No pointer events being registered at the second day is a bug I will treat in this issue: https://github.com/schedule-x/schedule-x/issues/801
