### ISSUE TITLE
schedule-x/react@2.10.0 unresolved dependency React 19

### ISSUE THREAD

**Issue by SqlOwl** [schedule-x/schedule-x#823]
Hi. I have an issue upgrading my project with Schedule-x v2.10.0 from NextJS 14 to version 15. Getting Following error:

Found: react@19.0.0
npm error node_modules/react
npm error   react@"19.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.7.0 || ^17 || ^18" from @schedule-x/react@2.10.0
npm error node_modules/@schedule-x/react
npm error   @schedule-x/react@"^2.10.0" from the root project

**Comment by tomosterlund** [comment]
Thanks for reporting

`^16.7.0 || ^17 || ^18` needs to be extended with 19, in @schedule-x/react

Feel like opening a PR? I'll probably get to it sometime this week otherwise, but can't say when yet

**Comment by SqlOwl** [comment]
Hi. I have been doing NextJS upgrade this week and Schedule-X could not resolve dependencies as upgrade took us to React 19. I solved it for now by levering package requirements to ^18. seemed to work, but I have not tested the calendar functionality yet. I am going to do so this weekend. It would be greatly beneficial if you add support for React 19.
