### ISSUE TITLE
Bug Report: Calendar Select View Not Updating Properly in Custom Header

### ISSUE THREAD

**Issue by iam-sreekanth** [schedule-x/schedule-x#824]
**Description:**
When using a custom header with the @schedule-x/react calendar, the Select component for changing views updates the calendar view successfully, but the selected value in the Select dropdown does not reflect the current calendar view.

**Steps to Reproduce:**

1. Create a calendar using @schedule-x/react and add the @schedule-x/calendar-controls plugin.
2. Define a custom header component with a Select dropdown bound to calendarControls.getView() for changing views.
3. Change the calendar view using the dropdown.
4. Observe that the calendar view updates, but the dropdown's selected value does not change.

**Expected Behavior:**
The Select dropdown value should reflect the current calendar view after changing views.

**Actual Behavior:**
The Select dropdown value remains unchanged, even though the calendar view updates correctly.

**Code Example:**

import { Box, Button, IconButton, MenuItem, Select, Typography } from '@mui/material';
import { ScheduleXCalendar, useCalendarApp } from '@schedule-x/react';
import React from 'react';
import { createViewDay, createViewMonthAgenda, createViewMonthGrid, createViewWeek } from '@schedule-x/calendar';
import { createEventsServicePlugin } from '@schedule-x/events-service';
import { createCalendarControlsPlugin } from '@schedule-x/calendar-controls';
import { DateTime } from 'luxon';
import { useGetMeetingsQuery } from '../../../services/meeting/meeting-service';
import './styles.css';

export default function MeetingsPage() {
  const { data: meetings } = useGetMeetingsQuery();
  const calendarControls = createCalendarControlsPlugin();

  const calendar = useCalendarApp({
    views: [createViewDay(), createViewWeek(), createViewMonthGrid(), createViewMonthAgenda()],
    plugins: [createEventsServicePlugin(), calendarControls],
  });

  const handleClick = (direction: 'next' | 'prev') => {
    const view = calendarControls.getView();
    const start = calendarControls.getRange()?.start;
    const end = calendarControls.getRange()?.end;

    if (!start || !end) {
      console.error('Dates are null or undefined');
      return;
    }

    const startDate = DateTime.fromFormat(start, 'yyyy-MM-dd HH:mm');
    const endDate = DateTime.fromFormat(end, 'yyyy-MM-dd HH:mm');

    let newDate: DateTime;

    switch (view) {
      case 'day':
        newDate = direction === 'next' ? endDate.plus({ days: 1 }) : startDate.minus({ days: 1 });
        break;
      case 'week':
        newDate = direction === 'next' ? endDate.plus({ weeks: 1 }) : startDate.minus({ weeks: 1 });
        break;
      case 'month-grid':
      case 'month-agenda':
        newDate = direction === 'next' ? endDate.plus({ months: 1 }) : startDate.minus({ months: 1 });
        break;
      default:
        console.error('Unknown view:', view);
        return;
    }

    calendarControls.setDate(newDate.toFormat('yyyy-MM-dd'));
  };

  return (
    <Box>
      <ScheduleXCalendar
        customComponents={{
          headerContent: () => (
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Button variant="contained">Today</Button>
              <IconButton onClick={() => handleClick('prev')}>
                {/* Left Arrow */}
              </IconButton>
              <Typography>{calendarControls.getRange()?.start}</Typography>
              <IconButton onClick={() => handleClick('next')}>
                {/* Right Arrow */}
              </IconButton>
              <Select
                value={calendarControls?.getView()}
                onChange={(e) => calendarControls.setView(e.target.value)}
              >
                {calendarControls
                  ?.getViews()
                  ?.map((view) => (
                    <MenuItem key={view.name} value={view.name}>
                      {view?.label}
                    </MenuItem>
                  ))}
              </Select>
            </Box>
          ),
        }}
        calendarApp={calendar}
      />
    </Box>
  );
}

**Date Range Formatter Code:**

export function formatDateRange(startDate: string, endDate: string): string {
  const start = DateTime.fromISO(startDate.replace(' ', 'T'));
  const end = DateTime.fromISO(endDate.replace(' ', 'T'));

  if (start.month === end.month && start.year === end.year) {
    return start.toFormat('MMMM yyyy');
  } else if (start.year === end.year) {
    return `${start.toFormat('MMMM')} – ${end.toFormat('MMMM yyyy')}`;
  } else {
    return `${start.toFormat('MMMM yyyy')} – ${end.toFormat('MMMM yyyy')}`;
  }
}

**Environment:**

- React: ^18.3.1
- @schedule-x/react: ^2.10.0
- @schedule-x/calendar-controls: ^2.11.0

**Potential Cause:**
The calendarControls.getView() method may not update synchronously with the calendar state, or it may not trigger a re-render of the header component.

**Attachments:**

https://github.com/user-attachments/assets/047d601c-a2c0-40bf-ad27-8be3c8fbcd66

**Comment by tomosterlund** [comment]
This problem has nothing to do with Schedule-X.

You need to manage state somehow in your custom header. `calendarControls?.getView()` won't update reactively, because it's a method, no reactive variable.

If you create some local state with `useState` and update it `onChange`, you can update the value of your select.

**Comment by iam-sreekanth** [comment]
Thank you for your feedback!

I created a local state in my page to manage the view:

const [view, setView] = React.useState<'day' | 'week' | 'month-grid'>('week');

I also updated the state in the Select component:

<Select
  size="medium"
  onChange={(e) => {
    setView(e.target.value as 'day' | 'week' | 'month-grid');
    calendarControls.setView(e.target.value);
  }}
  value={view}
  IconComponent={() => null}
  sx={{
    height: pxToRem(30),
    bgcolor: (theme) => theme.palette.primary.main,
    color: '#fff',
    width: pxToRem(60),
    textAlign: 'center',
    '& .MuiSelect-select': {
      padding: '0 !important',
    },
  }}
>
  {calendarControls
    ?.getViews()
    ?.slice(0, 3)
    ?.map((view) => (
      <MenuItem key={view.name} value={view.name}>
        {view.label}
      </MenuItem>
    ))}
</Select>

The view state updates correctly. However, the Select component does not reflect the updated value, and the headerContent does not seem to re-render. For instance, when I display the view like this inside the custom header:

<Typography variant="h4">{view}</Typography>

The value remains unchanged, suggesting that headerContent is not re-rendering when the state updates.

Could this be because ScheduleXCalendar treats headerContent as static and doesn’t observe state changes? Is there a recommended way to make the headerContent reactive to state updates?

Looking forward to your guidance!
