### ISSUE TITLE
Svelte 5 Compatibility

### ISSUE THREAD

**Issue by ebrenner-code** [schedule-x/schedule-x#838]
With the latest version of "@schedule-x/svelte": "^2.1.0", there's a dependency conflict for svelte 5. Running --force works and I see no errors using schdule-x with svelte 5 so far. A quick check that the breaking changes (https://svelte.dev/docs/svelte/v5-migration-guide#Breaking-changes-in-runes-mode) do not affect this package and a change to the dependencies would be welcome.

**Comment by tomosterlund** [comment]
Thanks for reporting!

I'm afk for the next couple of days, but would be open to merging a PR which fixes this in the package.json of schedule-x/svelte

**Comment by HunterLiddell** [comment]
@tomosterlund 
I just wrote this on the svelte repo as well. Feel free to do what you need with that. 
https://github.com/schedule-x/svelte/issues/42
